/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Source: https://github.com/GS-AX/confluence-weaver
*/
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ConfluenceWeaverPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian7 = require("obsidian");

// src/jiraWeaverBridge.ts
async function buildUrlMap(app) {
  const map = /* @__PURE__ */ new Map();
  const files = app.vault.getMarkdownFiles();
  for (const file of files) {
    const content = await app.vault.read(file);
    const urlMatch = content.match(/^confluence_url:\s*["']?([^\s"'\n]+)["']?/m);
    if (!urlMatch)
      continue;
    const rawUrl = urlMatch[1].trim();
    const normalizedUrl = rawUrl.replace(/[?#].*$/, "").replace(/\/$/, "");
    const wikiName = file.path.replace(/\.md$/, "");
    map.set(normalizedUrl, wikiName);
  }
  return map;
}
function isJiraWeaverFile(content) {
  return /^jira_id:/m.test(content);
}
function replaceConfluenceUrls(body, urlMap) {
  let count = 0;
  let result = body;
  for (const [url, wikiName] of urlMap) {
    const escaped = url.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    const mdLinkRe = new RegExp(`\\[([^\\]]+)\\]\\(${escaped}[^)]*\\)`, "g");
    result = result.replace(mdLinkRe, (_m, text) => {
      count++;
      return `[[${wikiName}|${text}]]`;
    });
    const bareRe = new RegExp(`(?<!\\()${escaped}(?:[^\\s)\\]"]*)?`, "g");
    result = result.replace(bareRe, () => {
      count++;
      return `[[${wikiName}]]`;
    });
  }
  return { result, count };
}
async function linkJiraPages(app) {
  const urlMap = await buildUrlMap(app);
  if (urlMap.size === 0)
    return 0;
  const files = app.vault.getMarkdownFiles();
  let totalReplaced = 0;
  for (const file of files) {
    const content = await app.vault.read(file);
    if (!isJiraWeaverFile(content))
      continue;
    const fmEnd = findFrontmatterEnd(content);
    const frontmatter = content.slice(0, fmEnd);
    const body = content.slice(fmEnd);
    const { result, count } = replaceConfluenceUrls(body, urlMap);
    if (count === 0)
      continue;
    await app.vault.modify(file, frontmatter + result);
    totalReplaced += count;
  }
  return totalReplaced;
}
function findFrontmatterEnd(content) {
  if (!content.startsWith("---"))
    return 0;
  const rest = content.slice(3);
  const closeIdx = rest.search(/\n---\s*\n/);
  if (closeIdx === -1)
    return 0;
  return closeIdx + 3 + "\n---\n".length;
}

// src/urlPageModal.ts
var import_obsidian = require("obsidian");

// src/i18n/en.ts
var en = {
  "setting.title": "Confluence Weaver",
  "setting.connection": "Connection",
  "setting.domain": "Confluence domain",
  "setting.domain.desc": "e.g. https://mycompany.atlassian.net/wiki",
  "setting.authMode": "Auth mode",
  "setting.authMode.basic": "Basic auth (Cloud)",
  "setting.authMode.bearer": "Bearer token (DC/Server)",
  "setting.email": "Email",
  "setting.email.desc": "Used with Basic auth (Cloud)",
  "setting.token": "Personal Access Token",
  "setting.token.desc": "API token (Cloud) or PAT (DC/Server)",
  "setting.testConnection": "Test connection",
  "setting.profiles": "CQL Profiles",
  "setting.addProfile": "+ Add profile",
  "setting.editProfile": "Edit",
  "setting.deleteProfile": "Delete",
  "setting.sync": "Sync Settings",
  "setting.syncOnStartup": "Sync on startup",
  "setting.syncOnStartup.desc": "Run sync when Obsidian opens",
  "setting.syncInterval": "Sync interval (minutes)",
  "setting.syncInterval.desc": "0 = disabled, 1\u20131440",
  "setting.missingMarker": "Missing marker behavior",
  "setting.missingMarker.desc": "What to do when the section marker is absent",
  "setting.missingMarker.overwrite": "Overwrite",
  "setting.missingMarker.skip": "Skip",
  "setting.folderHierarchy": "Preserve folder hierarchy",
  "setting.folderHierarchy.desc": "Mirror Confluence ancestor pages as folders",
  "setting.wikiLinks": "Convert Confluence links to wiki-links",
  "setting.wikiLinks.desc": "Replace [[ac:link]] with Obsidian [[wiki-link]] during conversion",
  "setting.downloadAttachments": "Download images",
  "setting.downloadAttachments.desc": "Save attached images to _attachments/{pageId}/ and embed them locally",
  "setting.language": "Language",
  "setting.language.desc": "Interface language (restart not required)",
  "setting.language.auto": "Auto (system)",
  "setting.language.en": "English",
  "setting.language.ko": "\uD55C\uAD6D\uC5B4",
  "setting.language.ja": "\u65E5\u672C\u8A9E",
  "setting.language.zh": "\u7B80\u4F53\u4E2D\u6587",
  "setting.advanced": "Advanced",
  "setting.maxBodyLength": "Max body length (chars)",
  "setting.maxBodyLength.desc": "0 = unlimited",
  "setting.fieldMappings": "Custom field mappings",
  "setting.fieldMappings.desc": "One mapping per line: dotPath \u2192 frontmatterKey (e.g. space.key \u2192 project)",
  "cmd.sync": "Sync Pages",
  "cmd.forceSync": "Force Sync Pages (Overwrite All)",
  "cmd.openLog": "Open Sync Log",
  "cmd.linkJira": "Link Confluence Pages in Jira Notes",
  "cmd.fetchByUrl": "Fetch Page by URL",
  "notice.connecting": "Testing connection\u2026",
  "notice.connected": "Connection successful",
  "notice.connectFailed": "Connection failed: ",
  "notice.syncing": "Syncing\u2026",
  "notice.syncDone": "Sync complete",
  "notice.syncFailed": "Sync failed: ",
  "notice.linkJira": "Linking Confluence pages in Jira notes\u2026",
  "notice.linkJiraDone": "Linked {count} Confluence URLs in Jira notes.",
  "notice.linkJiraFailed": "Link failed: ",
  "log.title": "Confluence Weaver \u2014 Sync Log",
  "log.profile": "Profile",
  "log.created": "Created",
  "log.updated": "Updated",
  "log.skipped": "Skipped",
  "log.errors": "Errors",
  "log.lastSync": "Last sync",
  "log.never": "Never",
  "log.noStats": "No sync has run yet.",
  "modal.editProfile": "Edit CQL Profile",
  "modal.newProfile": "New CQL Profile",
  "modal.profileName": "Profile name",
  "modal.cql": "CQL query",
  "modal.folder": "Target folder",
  "modal.folder.desc": "Relative path inside the Vault",
  "modal.maxPages": "Max pages",
  "modal.save": "Save",
  "modal.cancel": "Cancel",
  "modal.url.title": "Fetch Page by URL",
  "modal.url.url": "Confluence page URL",
  "modal.url.url.desc": "Paste a Confluence page URL \u2014 Cloud, DC, or Server",
  "modal.url.folder": "Save to folder",
  "modal.url.children": "Include child pages",
  "modal.url.children.desc": "Also fetch direct child pages of this page",
  "modal.url.descendants": "Include all descendants (recursive)",
  "modal.url.descendants.desc": "Recursively fetch all pages in the subtree",
  "modal.url.maxPages": "Max pages to fetch",
  "modal.url.fetch": "Fetch",
  "notice.url.fetching": "Fetching pages\u2026",
  "notice.url.done": "Fetched {created} new, {updated} updated.",
  "notice.url.invalidUrl": "Could not extract a page ID from this URL.",
  "notice.url.failed": "Fetch failed: "
};
var en_default = en;

// src/i18n/ko.ts
var ko = {
  "setting.title": "Confluence Weaver",
  "setting.connection": "\uC5F0\uACB0",
  "setting.domain": "Confluence \uB3C4\uBA54\uC778",
  "setting.domain.desc": "\uC608: https://mycompany.atlassian.net/wiki",
  "setting.authMode": "\uC778\uC99D \uBC29\uC2DD",
  "setting.authMode.basic": "Basic auth (Cloud)",
  "setting.authMode.bearer": "Bearer token (DC/Server)",
  "setting.email": "\uC774\uBA54\uC77C",
  "setting.email.desc": "Basic auth (Cloud) \uC0AC\uC6A9 \uC2DC \uC785\uB825",
  "setting.token": "\uAC1C\uC778 \uC561\uC138\uC2A4 \uD1A0\uD070",
  "setting.token.desc": "API \uD1A0\uD070 (Cloud) \uB610\uB294 PAT (DC/Server)",
  "setting.testConnection": "\uC5F0\uACB0 \uD14C\uC2A4\uD2B8",
  "setting.profiles": "CQL \uD504\uB85C\uD30C\uC77C",
  "setting.addProfile": "+ \uD504\uB85C\uD30C\uC77C \uCD94\uAC00",
  "setting.editProfile": "\uD3B8\uC9D1",
  "setting.deleteProfile": "\uC0AD\uC81C",
  "setting.sync": "\uC2F1\uD06C \uC124\uC815",
  "setting.syncOnStartup": "\uC2DC\uC791 \uC2DC \uC2F1\uD06C",
  "setting.syncOnStartup.desc": "Obsidian \uC5F4\uB9B4 \uB54C \uC790\uB3D9 \uC2F1\uD06C",
  "setting.syncInterval": "\uC2F1\uD06C \uC8FC\uAE30 (\uBD84)",
  "setting.syncInterval.desc": "0 = \uBE44\uD65C\uC131, 1\u20131440",
  "setting.missingMarker": "\uB9C8\uCEE4 \uC5C6\uB294 \uD30C\uC77C \uCC98\uB9AC",
  "setting.missingMarker.desc": "\uC139\uC158 \uB9C8\uCEE4\uAC00 \uC5C6\uC744 \uB54C \uB3D9\uC791",
  "setting.missingMarker.overwrite": "\uB36E\uC5B4\uC4F0\uAE30",
  "setting.missingMarker.skip": "\uAC74\uB108\uB6F0\uAE30",
  "setting.folderHierarchy": "\uACC4\uCE35 \uAD6C\uC870 \uD3F4\uB354 \uBC18\uC601",
  "setting.folderHierarchy.desc": "Confluence \uC0C1\uC704 \uD398\uC774\uC9C0\uB97C \uD3F4\uB354\uB85C \uBC18\uC601",
  "setting.wikiLinks": "Confluence \uB9C1\uD06C\uB97C wiki-link\uB85C \uBCC0\uD658",
  "setting.wikiLinks.desc": "\uBCC0\uD658 \uC2DC [[ac:link]]\uB97C Obsidian [[wiki-link]]\uB85C \uB300\uCCB4",
  "setting.downloadAttachments": "\uC774\uBBF8\uC9C0 \uB2E4\uC6B4\uB85C\uB4DC",
  "setting.downloadAttachments.desc": "\uCCA8\uBD80 \uC774\uBBF8\uC9C0\uB97C _attachments/{pageId}/ \uD3F4\uB354\uC5D0 \uC800\uC7A5\uD558\uACE0 \uB85C\uCEEC \uC784\uBCA0\uB4DC\uB85C \uBCC0\uD658",
  "setting.language": "\uC5B8\uC5B4",
  "setting.language.desc": "\uC778\uD130\uD398\uC774\uC2A4 \uC5B8\uC5B4 (\uC7AC\uC2DC\uC791 \uBD88\uD544\uC694)",
  "setting.language.auto": "\uC790\uB3D9 (\uC2DC\uC2A4\uD15C)",
  "setting.language.en": "English",
  "setting.language.ko": "\uD55C\uAD6D\uC5B4",
  "setting.language.ja": "\u65E5\u672C\u8A9E",
  "setting.language.zh": "\u7B80\u4F53\u4E2D\u6587",
  "setting.advanced": "\uACE0\uAE09",
  "setting.maxBodyLength": "\uCD5C\uB300 \uBCF8\uBB38 \uAE38\uC774 (\uBB38\uC790)",
  "setting.maxBodyLength.desc": "0 = \uC81C\uD55C \uC5C6\uC74C",
  "setting.fieldMappings": "\uC0AC\uC6A9\uC790 \uC815\uC758 \uD544\uB4DC \uB9E4\uD551",
  "setting.fieldMappings.desc": "\uC904\uB2F9 \uD558\uB098: dotPath \u2192 frontmatterKey (\uC608: space.key \u2192 project)",
  "cmd.sync": "\uD398\uC774\uC9C0 \uC2F1\uD06C",
  "cmd.forceSync": "\uD398\uC774\uC9C0 \uAC15\uC81C \uC2F1\uD06C (\uC804\uCCB4 \uB36E\uC5B4\uC4F0\uAE30)",
  "cmd.openLog": "\uC2F1\uD06C \uB85C\uADF8 \uC5F4\uAE30",
  "cmd.linkJira": "Jira \uB178\uD2B8\uC5D0 Confluence \uD398\uC774\uC9C0 \uC5F0\uACB0",
  "cmd.fetchByUrl": "URL\uB85C \uD398\uC774\uC9C0 \uBD88\uB7EC\uC624\uAE30",
  "notice.connecting": "\uC5F0\uACB0 \uD14C\uC2A4\uD2B8 \uC911\u2026",
  "notice.connected": "\uC5F0\uACB0 \uC131\uACF5",
  "notice.connectFailed": "\uC5F0\uACB0 \uC2E4\uD328: ",
  "notice.syncing": "\uC2F1\uD06C \uC911\u2026",
  "notice.syncDone": "\uC2F1\uD06C \uC644\uB8CC",
  "notice.syncFailed": "\uC2F1\uD06C \uC2E4\uD328: ",
  "notice.linkJira": "Jira \uB178\uD2B8\uC5D0 Confluence \uD398\uC774\uC9C0\uB97C \uC5F0\uACB0\uD558\uB294 \uC911\u2026",
  "notice.linkJiraDone": "Jira \uB178\uD2B8\uC5D0\uC11C Confluence URL {count}\uAC1C\uB97C wiki-link\uB85C \uBCC0\uD658\uD588\uC2B5\uB2C8\uB2E4.",
  "notice.linkJiraFailed": "\uC5F0\uACB0 \uC2E4\uD328: ",
  "log.title": "Confluence Weaver \u2014 \uC2F1\uD06C \uB85C\uADF8",
  "log.profile": "\uD504\uB85C\uD30C\uC77C",
  "log.created": "\uC0DD\uC131",
  "log.updated": "\uC5C5\uB370\uC774\uD2B8",
  "log.skipped": "\uAC74\uB108\uB700",
  "log.errors": "\uC624\uB958",
  "log.lastSync": "\uB9C8\uC9C0\uB9C9 \uC2F1\uD06C",
  "log.never": "\uC5C6\uC74C",
  "log.noStats": "\uC544\uC9C1 \uC2F1\uD06C\uAC00 \uC2E4\uD589\uB418\uC9C0 \uC54A\uC558\uC2B5\uB2C8\uB2E4.",
  "modal.editProfile": "CQL \uD504\uB85C\uD30C\uC77C \uD3B8\uC9D1",
  "modal.newProfile": "\uC0C8 CQL \uD504\uB85C\uD30C\uC77C",
  "modal.profileName": "\uD504\uB85C\uD30C\uC77C \uC774\uB984",
  "modal.cql": "CQL \uCFFC\uB9AC",
  "modal.folder": "\uB300\uC0C1 \uD3F4\uB354",
  "modal.folder.desc": "Vault \uB0B4 \uC0C1\uB300 \uACBD\uB85C",
  "modal.maxPages": "\uCD5C\uB300 \uD398\uC774\uC9C0 \uC218",
  "modal.save": "\uC800\uC7A5",
  "modal.cancel": "\uCDE8\uC18C",
  "modal.url.title": "URL\uB85C \uD398\uC774\uC9C0 \uBD88\uB7EC\uC624\uAE30",
  "modal.url.url": "Confluence \uD398\uC774\uC9C0 URL",
  "modal.url.url.desc": "Cloud, DC, Server URL \uBAA8\uB450 \uC9C0\uC6D0\uD569\uB2C8\uB2E4",
  "modal.url.folder": "\uC800\uC7A5 \uD3F4\uB354",
  "modal.url.children": "\uD558\uC704 \uD398\uC774\uC9C0 \uD3EC\uD568",
  "modal.url.children.desc": "\uC774 \uD398\uC774\uC9C0\uC758 \uC9C1\uC18D \uD558\uC704 \uD398\uC774\uC9C0\uB3C4 \uD568\uAED8 \uBD88\uB7EC\uC635\uB2C8\uB2E4",
  "modal.url.descendants": "\uBAA8\uB4E0 \uD558\uC704 \uD398\uC774\uC9C0 \uD3EC\uD568 (\uC7AC\uADC0)",
  "modal.url.descendants.desc": "\uD558\uC704 \uD2B8\uB9AC\uC758 \uBAA8\uB4E0 \uD398\uC774\uC9C0\uB97C \uC7AC\uADC0\uC801\uC73C\uB85C \uBD88\uB7EC\uC635\uB2C8\uB2E4",
  "modal.url.maxPages": "\uCD5C\uB300 \uD398\uC774\uC9C0 \uC218",
  "modal.url.fetch": "\uBD88\uB7EC\uC624\uAE30",
  "notice.url.fetching": "\uD398\uC774\uC9C0\uB97C \uBD88\uB7EC\uC624\uB294 \uC911\u2026",
  "notice.url.done": "{created}\uAC1C \uC0DD\uC131, {updated}\uAC1C \uC5C5\uB370\uC774\uD2B8 \uC644\uB8CC.",
  "notice.url.invalidUrl": "URL\uC5D0\uC11C \uD398\uC774\uC9C0 ID\uB97C \uCD94\uCD9C\uD560 \uC218 \uC5C6\uC2B5\uB2C8\uB2E4.",
  "notice.url.failed": "\uBD88\uB7EC\uC624\uAE30 \uC2E4\uD328: "
};
var ko_default = ko;

// src/i18n/ja.ts
var ja = {
  "setting.title": "Confluence Weaver",
  "setting.connection": "\u63A5\u7D9A",
  "setting.domain": "Confluence\u30C9\u30E1\u30A4\u30F3",
  "setting.domain.desc": "\u4F8B: https://mycompany.atlassian.net/wiki",
  "setting.authMode": "\u8A8D\u8A3C\u65B9\u5F0F",
  "setting.authMode.basic": "Basic\u8A8D\u8A3C (Cloud)",
  "setting.authMode.bearer": "Bearer\u30C8\u30FC\u30AF\u30F3 (DC/Server)",
  "setting.email": "\u30E1\u30FC\u30EB\u30A2\u30C9\u30EC\u30B9",
  "setting.email.desc": "Basic\u8A8D\u8A3C (Cloud) \u3067\u4F7F\u7528",
  "setting.token": "\u500B\u4EBA\u30A2\u30AF\u30BB\u30B9\u30C8\u30FC\u30AF\u30F3",
  "setting.token.desc": "API\u30C8\u30FC\u30AF\u30F3 (Cloud) \u307E\u305F\u306FPAT (DC/Server)",
  "setting.testConnection": "\u63A5\u7D9A\u30C6\u30B9\u30C8",
  "setting.profiles": "CQL\u30D7\u30ED\u30D5\u30A1\u30A4\u30EB",
  "setting.addProfile": "+ \u30D7\u30ED\u30D5\u30A1\u30A4\u30EB\u3092\u8FFD\u52A0",
  "setting.editProfile": "\u7DE8\u96C6",
  "setting.deleteProfile": "\u524A\u9664",
  "setting.sync": "\u540C\u671F\u8A2D\u5B9A",
  "setting.syncOnStartup": "\u8D77\u52D5\u6642\u306B\u540C\u671F",
  "setting.syncOnStartup.desc": "Obsidian\u8D77\u52D5\u6642\u306B\u81EA\u52D5\u540C\u671F",
  "setting.syncInterval": "\u540C\u671F\u9593\u9694 (\u5206)",
  "setting.syncInterval.desc": "0 = \u7121\u52B9, 1\u20131440",
  "setting.missingMarker": "\u30DE\u30FC\u30AB\u30FC\u6B20\u5982\u6642\u306E\u52D5\u4F5C",
  "setting.missingMarker.desc": "\u30BB\u30AF\u30B7\u30E7\u30F3\u30DE\u30FC\u30AB\u30FC\u304C\u5B58\u5728\u3057\u306A\u3044\u5834\u5408\u306E\u51E6\u7406",
  "setting.missingMarker.overwrite": "\u4E0A\u66F8\u304D",
  "setting.missingMarker.skip": "\u30B9\u30AD\u30C3\u30D7",
  "setting.folderHierarchy": "\u30D5\u30A9\u30EB\u30C0\u968E\u5C64\u3092\u7DAD\u6301",
  "setting.folderHierarchy.desc": "Confluence\u306E\u7956\u5148\u30DA\u30FC\u30B8\u3092\u30D5\u30A9\u30EB\u30C0\u3068\u3057\u3066\u53CD\u6620",
  "setting.wikiLinks": "Confluence\u30EA\u30F3\u30AF\u3092wiki-link\u306B\u5909\u63DB",
  "setting.wikiLinks.desc": "\u5909\u63DB\u6642\u306B[[ac:link]]\u3092Obsidian [[wiki-link]]\u306B\u7F6E\u63DB",
  "setting.downloadAttachments": "\u753B\u50CF\u3092\u30C0\u30A6\u30F3\u30ED\u30FC\u30C9",
  "setting.downloadAttachments.desc": "\u6DFB\u4ED8\u753B\u50CF\u3092 _attachments/{pageId}/ \u306B\u4FDD\u5B58\u3057\u3066\u30ED\u30FC\u30AB\u30EB\u3067\u57CB\u3081\u8FBC\u3080",
  "setting.language": "\u8A00\u8A9E",
  "setting.language.desc": "\u30A4\u30F3\u30BF\u30FC\u30D5\u30A7\u30FC\u30B9\u8A00\u8A9E\uFF08\u518D\u8D77\u52D5\u4E0D\u8981\uFF09",
  "setting.language.auto": "\u81EA\u52D5\uFF08\u30B7\u30B9\u30C6\u30E0\uFF09",
  "setting.language.en": "English",
  "setting.language.ko": "\uD55C\uAD6D\uC5B4",
  "setting.language.ja": "\u65E5\u672C\u8A9E",
  "setting.language.zh": "\u7B80\u4F53\u4E2D\u6587",
  "setting.advanced": "\u8A73\u7D30\u8A2D\u5B9A",
  "setting.maxBodyLength": "\u672C\u6587\u306E\u6700\u5927\u6587\u5B57\u6570",
  "setting.maxBodyLength.desc": "0 = \u5236\u9650\u306A\u3057",
  "setting.fieldMappings": "\u30AB\u30B9\u30BF\u30E0\u30D5\u30A3\u30FC\u30EB\u30C9\u30DE\u30C3\u30D4\u30F3\u30B0",
  "setting.fieldMappings.desc": "1\u884C1\u30DE\u30C3\u30D4\u30F3\u30B0: dotPath \u2192 frontmatterKey (\u4F8B: space.key \u2192 project)",
  "cmd.sync": "\u30DA\u30FC\u30B8\u3092\u540C\u671F",
  "cmd.forceSync": "\u30DA\u30FC\u30B8\u3092\u5F37\u5236\u540C\u671F (\u5168\u3066\u4E0A\u66F8\u304D)",
  "cmd.openLog": "\u540C\u671F\u30ED\u30B0\u3092\u958B\u304F",
  "cmd.linkJira": "Jira\u30CE\u30FC\u30C8\u306BConfluence\u30DA\u30FC\u30B8\u3092\u30EA\u30F3\u30AF",
  "cmd.fetchByUrl": "URL\u3067\u30DA\u30FC\u30B8\u3092\u53D6\u5F97",
  "notice.connecting": "\u63A5\u7D9A\u30C6\u30B9\u30C8\u4E2D\u2026",
  "notice.connected": "\u63A5\u7D9A\u6210\u529F",
  "notice.connectFailed": "\u63A5\u7D9A\u5931\u6557: ",
  "notice.syncing": "\u540C\u671F\u4E2D\u2026",
  "notice.syncDone": "\u540C\u671F\u5B8C\u4E86",
  "notice.syncFailed": "\u540C\u671F\u5931\u6557: ",
  "notice.linkJira": "Jira\u30CE\u30FC\u30C8\u306BConfluence\u30DA\u30FC\u30B8\u3092\u30EA\u30F3\u30AF\u4E2D\u2026",
  "notice.linkJiraDone": "Jira\u30CE\u30FC\u30C8\u306EConfluence URL {count}\u4EF6\u3092wiki-link\u306B\u5909\u63DB\u3057\u307E\u3057\u305F\u3002",
  "notice.linkJiraFailed": "\u30EA\u30F3\u30AF\u5931\u6557: ",
  "log.title": "Confluence Weaver \u2014 \u540C\u671F\u30ED\u30B0",
  "log.profile": "\u30D7\u30ED\u30D5\u30A1\u30A4\u30EB",
  "log.created": "\u4F5C\u6210",
  "log.updated": "\u66F4\u65B0",
  "log.skipped": "\u30B9\u30AD\u30C3\u30D7",
  "log.errors": "\u30A8\u30E9\u30FC",
  "log.lastSync": "\u6700\u7D42\u540C\u671F",
  "log.never": "\u306A\u3057",
  "log.noStats": "\u307E\u3060\u540C\u671F\u304C\u5B9F\u884C\u3055\u308C\u3066\u3044\u307E\u305B\u3093\u3002",
  "modal.editProfile": "CQL\u30D7\u30ED\u30D5\u30A1\u30A4\u30EB\u3092\u7DE8\u96C6",
  "modal.newProfile": "\u65B0\u3057\u3044CQL\u30D7\u30ED\u30D5\u30A1\u30A4\u30EB",
  "modal.profileName": "\u30D7\u30ED\u30D5\u30A1\u30A4\u30EB\u540D",
  "modal.cql": "CQL\u30AF\u30A8\u30EA",
  "modal.folder": "\u5BFE\u8C61\u30D5\u30A9\u30EB\u30C0",
  "modal.folder.desc": "Vault\u5185\u306E\u76F8\u5BFE\u30D1\u30B9",
  "modal.maxPages": "\u6700\u5927\u30DA\u30FC\u30B8\u6570",
  "modal.save": "\u4FDD\u5B58",
  "modal.cancel": "\u30AD\u30E3\u30F3\u30BB\u30EB",
  "modal.url.title": "URL\u3067\u30DA\u30FC\u30B8\u3092\u53D6\u5F97",
  "modal.url.url": "Confluence\u30DA\u30FC\u30B8URL",
  "modal.url.url.desc": "Cloud\u30FBDC\u30FBServer \u306EURL\u3092\u30DA\u30FC\u30B9\u30C8\u3057\u3066\u304F\u3060\u3055\u3044",
  "modal.url.folder": "\u4FDD\u5B58\u5148\u30D5\u30A9\u30EB\u30C0",
  "modal.url.children": "\u5B50\u30DA\u30FC\u30B8\u3092\u542B\u3081\u308B",
  "modal.url.children.desc": "\u3053\u306E\u30DA\u30FC\u30B8\u306E\u76F4\u4E0B\u306E\u5B50\u30DA\u30FC\u30B8\u3082\u53D6\u5F97\u3057\u307E\u3059",
  "modal.url.descendants": "\u3059\u3079\u3066\u306E\u5B50\u5B6B\u30DA\u30FC\u30B8\u3092\u542B\u3081\u308B (\u518D\u5E30)",
  "modal.url.descendants.desc": "\u30B5\u30D6\u30C4\u30EA\u30FC\u5185\u306E\u3059\u3079\u3066\u306E\u30DA\u30FC\u30B8\u3092\u518D\u5E30\u7684\u306B\u53D6\u5F97\u3057\u307E\u3059",
  "modal.url.maxPages": "\u6700\u5927\u30DA\u30FC\u30B8\u6570",
  "modal.url.fetch": "\u53D6\u5F97",
  "notice.url.fetching": "\u30DA\u30FC\u30B8\u3092\u53D6\u5F97\u4E2D\u2026",
  "notice.url.done": "{created}\u4EF6\u4F5C\u6210\u3001{updated}\u4EF6\u66F4\u65B0\u3057\u307E\u3057\u305F\u3002",
  "notice.url.invalidUrl": "URL\u304B\u3089\u30DA\u30FC\u30B8ID\u3092\u62BD\u51FA\u3067\u304D\u307E\u305B\u3093\u3067\u3057\u305F\u3002",
  "notice.url.failed": "\u53D6\u5F97\u5931\u6557: "
};
var ja_default = ja;

// src/i18n/zh.ts
var zh = {
  "setting.title": "Confluence Weaver",
  "setting.connection": "\u8FDE\u63A5",
  "setting.domain": "Confluence \u57DF\u540D",
  "setting.domain.desc": "\u4F8B\u5982: https://mycompany.atlassian.net/wiki",
  "setting.authMode": "\u8BA4\u8BC1\u65B9\u5F0F",
  "setting.authMode.basic": "Basic \u8BA4\u8BC1 (Cloud)",
  "setting.authMode.bearer": "Bearer \u4EE4\u724C (DC/Server)",
  "setting.email": "\u7535\u5B50\u90AE\u4EF6",
  "setting.email.desc": "\u7528\u4E8E Basic \u8BA4\u8BC1 (Cloud)",
  "setting.token": "\u4E2A\u4EBA\u8BBF\u95EE\u4EE4\u724C",
  "setting.token.desc": "API \u4EE4\u724C (Cloud) \u6216 PAT (DC/Server)",
  "setting.testConnection": "\u6D4B\u8BD5\u8FDE\u63A5",
  "setting.profiles": "CQL \u914D\u7F6E\u6587\u4EF6",
  "setting.addProfile": "+ \u6DFB\u52A0\u914D\u7F6E\u6587\u4EF6",
  "setting.editProfile": "\u7F16\u8F91",
  "setting.deleteProfile": "\u5220\u9664",
  "setting.sync": "\u540C\u6B65\u8BBE\u7F6E",
  "setting.syncOnStartup": "\u542F\u52A8\u65F6\u540C\u6B65",
  "setting.syncOnStartup.desc": "\u6253\u5F00 Obsidian \u65F6\u81EA\u52A8\u540C\u6B65",
  "setting.syncInterval": "\u540C\u6B65\u95F4\u9694 (\u5206\u949F)",
  "setting.syncInterval.desc": "0 = \u7981\u7528, 1\u20131440",
  "setting.missingMarker": "\u7F3A\u5C11\u6807\u8BB0\u65F6\u7684\u5904\u7406",
  "setting.missingMarker.desc": "\u5F53\u5206\u533A\u6807\u8BB0\u4E0D\u5B58\u5728\u65F6\u7684\u5904\u7406\u65B9\u5F0F",
  "setting.missingMarker.overwrite": "\u8986\u76D6",
  "setting.missingMarker.skip": "\u8DF3\u8FC7",
  "setting.folderHierarchy": "\u4FDD\u7559\u6587\u4EF6\u5939\u5C42\u7EA7",
  "setting.folderHierarchy.desc": "\u5C06 Confluence \u7956\u5148\u9875\u9762\u6620\u5C04\u4E3A\u6587\u4EF6\u5939",
  "setting.wikiLinks": "\u5C06 Confluence \u94FE\u63A5\u8F6C\u6362\u4E3A wiki-link",
  "setting.wikiLinks.desc": "\u8F6C\u6362\u65F6\u5C06 [[ac:link]] \u66FF\u6362\u4E3A Obsidian [[wiki-link]]",
  "setting.downloadAttachments": "\u4E0B\u8F7D\u56FE\u7247",
  "setting.downloadAttachments.desc": "\u5C06\u9644\u4EF6\u56FE\u7247\u4FDD\u5B58\u5230 _attachments/{pageId}/ \u5E76\u4F7F\u7528\u672C\u5730\u5D4C\u5165",
  "setting.language": "\u8BED\u8A00",
  "setting.language.desc": "\u754C\u9762\u8BED\u8A00\uFF08\u65E0\u9700\u91CD\u542F\uFF09",
  "setting.language.auto": "\u81EA\u52A8\uFF08\u7CFB\u7EDF\uFF09",
  "setting.language.en": "English",
  "setting.language.ko": "\uD55C\uAD6D\uC5B4",
  "setting.language.ja": "\u65E5\u672C\u8A9E",
  "setting.language.zh": "\u7B80\u4F53\u4E2D\u6587",
  "setting.advanced": "\u9AD8\u7EA7\u8BBE\u7F6E",
  "setting.maxBodyLength": "\u6700\u5927\u6B63\u6587\u957F\u5EA6 (\u5B57\u7B26)",
  "setting.maxBodyLength.desc": "0 = \u4E0D\u9650\u5236",
  "setting.fieldMappings": "\u81EA\u5B9A\u4E49\u5B57\u6BB5\u6620\u5C04",
  "setting.fieldMappings.desc": "\u6BCF\u884C\u4E00\u6761\u6620\u5C04: dotPath \u2192 frontmatterKey (\u4F8B\u5982: space.key \u2192 project)",
  "cmd.sync": "\u540C\u6B65\u9875\u9762",
  "cmd.forceSync": "\u5F3A\u5236\u540C\u6B65\u9875\u9762 (\u5168\u90E8\u8986\u76D6)",
  "cmd.openLog": "\u6253\u5F00\u540C\u6B65\u65E5\u5FD7",
  "cmd.linkJira": "\u5728 Jira \u7B14\u8BB0\u4E2D\u94FE\u63A5 Confluence \u9875\u9762",
  "cmd.fetchByUrl": "\u901A\u8FC7 URL \u83B7\u53D6\u9875\u9762",
  "notice.connecting": "\u6B63\u5728\u6D4B\u8BD5\u8FDE\u63A5\u2026",
  "notice.connected": "\u8FDE\u63A5\u6210\u529F",
  "notice.connectFailed": "\u8FDE\u63A5\u5931\u8D25: ",
  "notice.syncing": "\u6B63\u5728\u540C\u6B65\u2026",
  "notice.syncDone": "\u540C\u6B65\u5B8C\u6210",
  "notice.syncFailed": "\u540C\u6B65\u5931\u8D25: ",
  "notice.linkJira": "\u6B63\u5728 Jira \u7B14\u8BB0\u4E2D\u94FE\u63A5 Confluence \u9875\u9762\u2026",
  "notice.linkJiraDone": "\u5DF2\u5728 Jira \u7B14\u8BB0\u4E2D\u8F6C\u6362 {count} \u4E2A Confluence URL \u4E3A wiki-link\u3002",
  "notice.linkJiraFailed": "\u94FE\u63A5\u5931\u8D25: ",
  "log.title": "Confluence Weaver \u2014 \u540C\u6B65\u65E5\u5FD7",
  "log.profile": "\u914D\u7F6E\u6587\u4EF6",
  "log.created": "\u5DF2\u521B\u5EFA",
  "log.updated": "\u5DF2\u66F4\u65B0",
  "log.skipped": "\u5DF2\u8DF3\u8FC7",
  "log.errors": "\u9519\u8BEF",
  "log.lastSync": "\u6700\u540E\u540C\u6B65",
  "log.never": "\u4ECE\u672A",
  "log.noStats": "\u5C1A\u672A\u6267\u884C\u540C\u6B65\u3002",
  "modal.editProfile": "\u7F16\u8F91 CQL \u914D\u7F6E\u6587\u4EF6",
  "modal.newProfile": "\u65B0\u5EFA CQL \u914D\u7F6E\u6587\u4EF6",
  "modal.profileName": "\u914D\u7F6E\u6587\u4EF6\u540D\u79F0",
  "modal.cql": "CQL \u67E5\u8BE2",
  "modal.folder": "\u76EE\u6807\u6587\u4EF6\u5939",
  "modal.folder.desc": "Vault \u5185\u7684\u76F8\u5BF9\u8DEF\u5F84",
  "modal.maxPages": "\u6700\u5927\u9875\u6570",
  "modal.save": "\u4FDD\u5B58",
  "modal.cancel": "\u53D6\u6D88",
  "modal.url.title": "\u901A\u8FC7 URL \u83B7\u53D6\u9875\u9762",
  "modal.url.url": "Confluence \u9875\u9762 URL",
  "modal.url.url.desc": "\u652F\u6301 Cloud\u3001DC \u548C Server URL",
  "modal.url.folder": "\u4FDD\u5B58\u6587\u4EF6\u5939",
  "modal.url.children": "\u5305\u542B\u5B50\u9875\u9762",
  "modal.url.children.desc": "\u540C\u65F6\u83B7\u53D6\u6B64\u9875\u9762\u7684\u76F4\u63A5\u5B50\u9875\u9762",
  "modal.url.descendants": "\u5305\u542B\u6240\u6709\u540E\u4EE3\u9875\u9762\uFF08\u9012\u5F52\uFF09",
  "modal.url.descendants.desc": "\u9012\u5F52\u83B7\u53D6\u5B50\u6811\u4E2D\u7684\u6240\u6709\u9875\u9762",
  "modal.url.maxPages": "\u6700\u5927\u9875\u6570",
  "modal.url.fetch": "\u83B7\u53D6",
  "notice.url.fetching": "\u6B63\u5728\u83B7\u53D6\u9875\u9762\u2026",
  "notice.url.done": "\u5DF2\u521B\u5EFA {created} \u4E2A\uFF0C\u66F4\u65B0 {updated} \u4E2A\u3002",
  "notice.url.invalidUrl": "\u65E0\u6CD5\u4ECE\u8BE5 URL \u4E2D\u63D0\u53D6\u9875\u9762 ID\u3002",
  "notice.url.failed": "\u83B7\u53D6\u5931\u8D25: "
};
var zh_default = zh;

// src/i18n/index.ts
var LOCALES = { en: en_default, ko: ko_default, ja: ja_default, zh: zh_default };
var overrideLocale = null;
function setLocale(locale) {
  overrideLocale = locale === "auto" ? null : locale;
}
function detectLocale() {
  if (overrideLocale)
    return overrideLocale;
  const lang = window.navigator.language.toLowerCase();
  if (lang.startsWith("ko"))
    return "ko";
  if (lang.startsWith("ja"))
    return "ja";
  if (lang.startsWith("zh"))
    return "zh";
  return "en";
}
function t(key) {
  var _a, _b, _c;
  const locale = detectLocale();
  return (_c = (_b = (_a = LOCALES[locale]) == null ? void 0 : _a[key]) != null ? _b : LOCALES.en[key]) != null ? _c : key;
}

// src/urlPageModal.ts
var UrlPageModal = class extends import_obsidian.Modal {
  constructor(app, plugin) {
    var _a, _b;
    super(app);
    this.plugin = plugin;
    this.url = "";
    this.folder = "Confluence";
    this.includeChildren = false;
    this.allDescendants = false;
    this.maxPages = 100;
    this.folder = (_b = (_a = plugin.settings.profiles[0]) == null ? void 0 : _a.folder) != null ? _b : "Confluence";
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: t("modal.url.title") });
    new import_obsidian.Setting(contentEl).setName(t("modal.url.url")).setDesc(t("modal.url.url.desc")).addText((text) => {
      text.setPlaceholder("https://mycompany.atlassian.net/wiki/spaces/DEV/pages/123456").setValue(this.url).onChange((v) => {
        this.url = v.trim();
      });
      text.inputEl.addClass("cw-textarea");
    });
    new import_obsidian.Setting(contentEl).setName(t("modal.url.folder")).addText(
      (text) => text.setPlaceholder("Confluence").setValue(this.folder).onChange((v) => {
        this.folder = v.trim();
      })
    );
    const childrenSetting = new import_obsidian.Setting(contentEl).setName(t("modal.url.children")).setDesc(t("modal.url.children.desc")).addToggle(
      (toggle) => toggle.setValue(this.includeChildren).onChange((v) => {
        this.includeChildren = v;
        descendantsSetting.settingEl.toggle(v);
        maxPagesSetting.settingEl.toggle(v);
      })
    );
    const descendantsSetting = new import_obsidian.Setting(contentEl).setName(t("modal.url.descendants")).setDesc(t("modal.url.descendants.desc")).addToggle(
      (toggle) => toggle.setValue(this.allDescendants).onChange((v) => {
        this.allDescendants = v;
      })
    );
    const maxPagesSetting = new import_obsidian.Setting(contentEl).setName(t("modal.url.maxPages")).addText(
      (text) => text.setValue(String(this.maxPages)).onChange((v) => {
        this.maxPages = Math.max(1, parseInt(v) || 100);
      })
    );
    descendantsSetting.settingEl.toggle(this.includeChildren);
    maxPagesSetting.settingEl.toggle(this.includeChildren);
    new import_obsidian.Setting(contentEl).addButton(
      (btn) => btn.setButtonText(t("modal.url.fetch")).setCta().onClick(() => this.submit())
    ).addButton(
      (btn) => btn.setButtonText(t("modal.cancel")).onClick(() => this.close())
    );
  }
  async submit() {
    if (!this.url) {
      new import_obsidian.Notice(t("notice.url.invalidUrl"));
      return;
    }
    this.close();
    await this.plugin.fetchByUrl(
      this.url,
      this.folder,
      this.includeChildren,
      this.allDescendants,
      this.maxPages
    );
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/confluenceClient.ts
var import_obsidian2 = require("obsidian");
var ConfluenceClient = class {
  constructor(settings) {
    this.settings = settings;
  }
  get baseUrl() {
    return this.settings.domain.replace(/\/$/, "");
  }
  authHeader() {
    if (this.settings.authMode === "basic") {
      const creds = Buffer.from(`${this.settings.email}:${this.settings.token}`).toString("base64");
      return `Basic ${creds}`;
    }
    return `Bearer ${this.settings.token}`;
  }
  async get(path) {
    var _a;
    const url = `${this.baseUrl}${path}`;
    const resp = await (0, import_obsidian2.requestUrl)({
      url,
      method: "GET",
      headers: {
        Authorization: this.authHeader(),
        "Content-Type": "application/json",
        Accept: "application/json"
      }
    });
    if (resp.status >= 400) {
      const preview = ((_a = resp.text) != null ? _a : "").slice(0, 200);
      throw new Error(`${resp.status}${preview ? ": " + preview : ""}`);
    }
    return resp.json;
  }
  async testConnection() {
    await this.get("/rest/api/space?limit=1");
  }
  async searchCQL(cql, limit = 50) {
    var _a;
    const data = await this.get(
      `/rest/api/content/search?cql=${encodeURIComponent(cql)}&limit=${limit}&expand=version,space,ancestors`
    );
    return (_a = data.results) != null ? _a : [];
  }
  async getPage(id) {
    return this.get(
      `/rest/api/content/${id}?expand=body.storage,version,ancestors,space,metadata.labels,history`
    );
  }
  /**
   * Extract a page ID from any Confluence URL format:
   *  - /pages/123456/...          (Cloud & DC path)
   *  - pageId=123456              (DC viewpage.action query string)
   *  - /display/SPACE/Title       (DC display URL — resolves via title search)
   * Returns null when no ID can be extracted without an API call.
   */
  parsePageId(url) {
    const pathMatch = url.match(/\/pages\/(\d+)/);
    if (pathMatch)
      return pathMatch[1];
    const queryMatch = url.match(/[?&]pageId=(\d+)/);
    if (queryMatch)
      return queryMatch[1];
    return null;
  }
  /**
   * Resolve a Confluence /display/SPACE/Title URL by searching for the title.
   * Used as fallback when parsePageId returns null.
   */
  async resolveDisplayUrl(url) {
    var _a, _b;
    const displayMatch = url.match(/\/display\/([^/?#]+)\/([^?#]+)/);
    if (!displayMatch)
      return null;
    const spaceKey = decodeURIComponent(displayMatch[1]);
    const title = decodeURIComponent(displayMatch[2].replace(/\+/g, " "));
    const cql = `space = "${spaceKey}" AND title = "${title.replace(/"/g, '\\"')}"`;
    const results = await this.searchCQL(cql, 1);
    return (_b = (_a = results[0]) == null ? void 0 : _a.id) != null ? _b : null;
  }
  /** Fetch direct child pages (no body — IDs only for batch fetch). */
  async getChildPageIds(parentId) {
    var _a;
    let start = 0;
    const limit = 50;
    const ids = [];
    while (true) {
      const data = await this.get(
        `/rest/api/content/${parentId}/child/page?limit=${limit}&start=${start}`
      );
      const results = (_a = data.results) != null ? _a : [];
      ids.push(...results.map((r) => r.id));
      if (results.length < limit)
        break;
      start += limit;
    }
    return ids;
  }
  /**
   * Collect all descendant page IDs using BFS.
   * Stops when maxPages is reached to prevent runaway fetches.
   */
  async collectDescendantIds(rootId, maxPages) {
    const all = [];
    const queue = [rootId];
    while (queue.length > 0 && all.length < maxPages) {
      const id = queue.shift();
      const children = await this.getChildPageIds(id);
      for (const cid of children) {
        if (all.length >= maxPages)
          break;
        all.push(cid);
        queue.push(cid);
      }
    }
    return all;
  }
  async getPageProperties(id) {
    var _a;
    const data = await this.get(
      `/rest/api/content/${id}/property?limit=50`
    );
    return Object.fromEntries(((_a = data.results) != null ? _a : []).map((p) => [p.key, p.value]));
  }
  /** Fetch all attachments for a page. Returns image attachments by default. */
  async getPageAttachments(pageId, imagesOnly = true) {
    var _a, _b, _c;
    let start = 0;
    const limit = 50;
    const results = [];
    while (true) {
      const data = await this.get(
        `/rest/api/content/${pageId}/child/attachment?limit=${limit}&start=${start}&expand=metadata`
      );
      const batch = (_a = data.results) != null ? _a : [];
      for (const att of batch) {
        if (!imagesOnly || ((_c = (_b = att.metadata) == null ? void 0 : _b.mediaType) == null ? void 0 : _c.startsWith("image/"))) {
          results.push(att);
        }
      }
      if (batch.length < limit)
        break;
      start += limit;
    }
    return results;
  }
  /** Download a Confluence attachment and return its raw bytes. */
  async downloadAttachment(downloadPath) {
    const url = downloadPath.startsWith("http") ? downloadPath : `${this.baseUrl}${downloadPath}`;
    const resp = await (0, import_obsidian2.requestUrl)({
      url,
      method: "GET",
      headers: { Authorization: this.authHeader() }
    });
    if (resp.status >= 400) {
      throw new Error(`${resp.status}: attachment download failed`);
    }
    return resp.arrayBuffer;
  }
};

// src/fileManager.ts
var import_obsidian3 = require("obsidian");

// src/fieldResolver.ts
function yamlString(value) {
  const collapsed = value.replace(/\r?\n/g, " ").replace(/\r/g, " ");
  if (/[:#\[\]{}|>&*!,'"%@`]/.test(collapsed) || collapsed.trim() !== collapsed || collapsed === "") {
    return `"${collapsed.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
  }
  return collapsed;
}
function yamlDate(isoString) {
  return (isoString || "").split("T")[0];
}
function slugify(text) {
  return text.replace(/[\\/:*?"<>|]/g, "").replace(/\s+/g, "-").replace(/-{2,}/g, "-").replace(/^-+|-+$/g, "");
}

// src/fileManager.ts
var FileManager = class {
  constructor(app) {
    this.app = app;
  }
  async ensureFolder(folderPath) {
    var _a;
    const path = (0, import_obsidian3.normalizePath)(folderPath);
    if (!path || path === ".")
      return;
    const existing = this.app.vault.getAbstractFileByPath(path);
    if (existing instanceof import_obsidian3.TFolder)
      return;
    const parts = path.split("/");
    if (parts.length > 1) {
      await this.ensureFolder(parts.slice(0, -1).join("/"));
    }
    const after = this.app.vault.getAbstractFileByPath(path);
    if (!after) {
      try {
        await this.app.vault.createFolder(path);
      } catch (e) {
        if (!((_a = e.message) == null ? void 0 : _a.includes("already exists")))
          throw e;
      }
    }
  }
  async readFile(path) {
    const file = this.app.vault.getAbstractFileByPath((0, import_obsidian3.normalizePath)(path));
    return file instanceof import_obsidian3.TFile ? this.app.vault.read(file) : null;
  }
  async writeFile(path, content) {
    const normalized = (0, import_obsidian3.normalizePath)(path);
    const existing = this.app.vault.getAbstractFileByPath(normalized);
    if (existing instanceof import_obsidian3.TFile) {
      await this.app.vault.modify(existing, content);
      return "updated";
    }
    const parts = normalized.split("/");
    if (parts.length > 1) {
      await this.ensureFolder(parts.slice(0, -1).join("/"));
    }
    await this.app.vault.create(normalized, content);
    return "created";
  }
  async writeBinaryFile(path, data) {
    const normalized = (0, import_obsidian3.normalizePath)(path);
    const existing = this.app.vault.getAbstractFileByPath(normalized);
    if (existing instanceof import_obsidian3.TFile) {
      await this.app.vault.modifyBinary(existing, data);
      return "updated";
    }
    const parts = normalized.split("/");
    if (parts.length > 1) {
      await this.ensureFolder(parts.slice(0, -1).join("/"));
    }
    await this.app.vault.createBinary(normalized, data);
    return "created";
  }
  resolveFilePath(page, baseFolder, folderHierarchy) {
    var _a;
    const fileName = `${page.id}_${slugify(page.title)}.md`;
    if (folderHierarchy && ((_a = page.ancestors) == null ? void 0 : _a.length) > 0) {
      const ancestorPath = page.ancestors.map((a) => slugify(a.title)).join("/");
      const folder = baseFolder ? `${baseFolder}/${ancestorPath}` : ancestorPath;
      return (0, import_obsidian3.normalizePath)(`${folder}/${fileName}`);
    }
    return baseFolder ? (0, import_obsidian3.normalizePath)(`${baseFolder}/${fileName}`) : (0, import_obsidian3.normalizePath)(fileName);
  }
};

// src/types.ts
var SECTION_MARKER = "[confluence-weaver section end]";

// src/storageToMarkdown.ts
function escAttr(val) {
  return val.replace(/&/g, "&amp;").replace(/"/g, "&quot;");
}
function storageToMarkdown(html, options = {}) {
  const { wikiLinks = true } = options;
  let s = html;
  s = s.replace(
    /<ac:task-list[^>]*>([\s\S]*?)<\/ac:task-list>/gi,
    (_m, inner) => {
      var _a, _b, _c;
      const tasks = [];
      const taskRe = /<ac:task[^>]*>([\s\S]*?)<\/ac:task>/gi;
      let tm;
      while ((tm = taskRe.exec(inner)) !== null) {
        const taskInner = tm[1];
        const statusMatch = taskInner.match(/<ac:task-status[^>]*>([\s\S]*?)<\/ac:task-status>/i);
        const bodyMatch = taskInner.match(/<ac:task-body[^>]*>([\s\S]*?)<\/ac:task-body>/i);
        const done = ((_a = statusMatch == null ? void 0 : statusMatch[1]) == null ? void 0 : _a.trim().toLowerCase()) === "complete";
        const body = (_c = (_b = bodyMatch == null ? void 0 : bodyMatch[1]) == null ? void 0 : _b.replace(/<[^>]+>/g, "").trim()) != null ? _c : "";
        tasks.push(`- [${done ? "x" : " "}] ${body}`);
      }
      return tasks.join("\n") + "\n";
    }
  );
  s = s.replace(
    /<ac:status\b[^>]*\bac:title="([^"]*)"[^>]*\/?>/gi,
    (_m, title) => `**${title}**`
  );
  s = s.replace(/<ac:emoticon[^>]*\/>/gi, "");
  s = s.replace(
    /<ac:structured-macro[^>]*\bac:name="toc"[^>]*>[\s\S]*?<\/ac:structured-macro>/gi,
    ""
  );
  s = s.replace(
    /<ac:structured-macro[^>]*\bac:name="code"[^>]*>([\s\S]*?)<\/ac:structured-macro>/gi,
    (_m, inner) => {
      var _a, _b;
      const langMatch = inner.match(/<ac:parameter[^>]*\bac:name="language"[^>]*>([\s\S]*?)<\/ac:parameter>/i);
      const lang = langMatch ? langMatch[1].trim() : "";
      const cdataMatch = inner.match(/<ac:plain-text-body[^>]*><!\[CDATA\[([\s\S]*?)\]\]><\/ac:plain-text-body>/i);
      const textMatch = inner.match(/<ac:plain-text-body[^>]*>([\s\S]*?)<\/ac:plain-text-body>/i);
      const code = (_b = (_a = cdataMatch != null ? cdataMatch : textMatch) == null ? void 0 : _a[1]) != null ? _b : "";
      return `
\`\`\`${lang}
${code}
\`\`\`
`;
    }
  );
  s = s.replace(
    /<ac:structured-macro[^>]*\bac:name="noformat"[^>]*>([\s\S]*?)<\/ac:structured-macro>/gi,
    (_m, inner) => {
      var _a, _b;
      const cdataMatch = inner.match(/<ac:plain-text-body[^>]*><!\[CDATA\[([\s\S]*?)\]\]><\/ac:plain-text-body>/i);
      const textMatch = inner.match(/<ac:plain-text-body[^>]*>([\s\S]*?)<\/ac:plain-text-body>/i);
      const code = (_b = (_a = cdataMatch != null ? cdataMatch : textMatch) == null ? void 0 : _a[1]) != null ? _b : "";
      return `
\`\`\`
${code}
\`\`\`
`;
    }
  );
  s = s.replace(
    /<ac:structured-macro[^>]*\bac:name="column"[^>]*>([\s\S]*?)<\/ac:structured-macro>/gi,
    (_m, inner) => {
      const bodyMatch = inner.match(/<ac:rich-text-body[^>]*>([\s\S]*?)<\/ac:rich-text-body>/i);
      return (bodyMatch ? bodyMatch[1] : "") + "\n<hr/>\n";
    }
  );
  s = s.replace(
    /<ac:structured-macro[^>]*\bac:name="section"[^>]*>([\s\S]*?)<\/ac:structured-macro>/gi,
    (_m, inner) => {
      const bodyMatch = inner.match(/<ac:rich-text-body[^>]*>([\s\S]*?)<\/ac:rich-text-body>/i);
      return bodyMatch ? bodyMatch[1] : "";
    }
  );
  s = s.replace(
    /<ac:structured-macro[^>]*\bac:name="panel"[^>]*>([\s\S]*?)<\/ac:structured-macro>/gi,
    (_m, inner) => {
      var _a, _b;
      const titleParam = inner.match(/<ac:parameter[^>]*\bac:name="title"[^>]*>([\s\S]*?)<\/ac:parameter>/i);
      const title = (_b = (_a = titleParam == null ? void 0 : titleParam[1]) == null ? void 0 : _a.trim()) != null ? _b : "";
      const bodyMatch = inner.match(/<ac:rich-text-body[^>]*>([\s\S]*?)<\/ac:rich-text-body>/i);
      const body = bodyMatch ? bodyMatch[1] : inner;
      return `<blockquote data-cw-type="abstract" data-cw-title="${escAttr(title)}">${body}</blockquote>`;
    }
  );
  s = s.replace(
    /<ac:structured-macro[^>]*\bac:name="expand"[^>]*>([\s\S]*?)<\/ac:structured-macro>/gi,
    (_m, inner) => {
      var _a, _b;
      const titleParam = inner.match(/<ac:parameter[^>]*\bac:name="title"[^>]*>([\s\S]*?)<\/ac:parameter>/i);
      const title = (_b = (_a = titleParam == null ? void 0 : titleParam[1]) == null ? void 0 : _a.trim()) != null ? _b : "Details";
      const bodyMatch = inner.match(/<ac:rich-text-body[^>]*>([\s\S]*?)<\/ac:rich-text-body>/i);
      const body = bodyMatch ? bodyMatch[1] : inner;
      return `<blockquote data-cw-type="abstract" data-cw-title="${escAttr(title)}" data-cw-collapse="true">${body}</blockquote>`;
    }
  );
  s = s.replace(
    /<ac:structured-macro[^>]*\bac:name="(info|note|warning|tip)"[^>]*>([\s\S]*?)<\/ac:structured-macro>/gi,
    (_m, type, inner) => {
      const bodyMatch = inner.match(/<ac:rich-text-body[^>]*>([\s\S]*?)<\/ac:rich-text-body>/i);
      const body = bodyMatch ? bodyMatch[1] : inner;
      return `<blockquote data-cw-type="${type}" data-cw-title="">${body}</blockquote>`;
    }
  );
  s = s.replace(
    /<ac:structured-macro[^>]*\bac:name="excerpt"[^>]*>([\s\S]*?)<\/ac:structured-macro>/gi,
    (_m, inner) => {
      const bodyMatch = inner.match(/<ac:rich-text-body[^>]*>([\s\S]*?)<\/ac:rich-text-body>/i);
      return bodyMatch ? bodyMatch[1] : "";
    }
  );
  s = s.replace(
    /<ac:structured-macro[^>]*\bac:name="excerpt-include"[^>]*>([\s\S]*?)<\/ac:structured-macro>/gi,
    (_m, inner) => {
      var _a;
      const pageMatch = inner.match(/ri:content-title="([^"]*)"/i);
      const page = (_a = pageMatch == null ? void 0 : pageMatch[1]) != null ? _a : "";
      return page ? `
> *Excerpt from [[${page}]]*
` : "";
    }
  );
  s = s.replace(
    /<ac:structured-macro[^>]*\bac:name="include"[^>]*>([\s\S]*?)<\/ac:structured-macro>/gi,
    (_m, inner) => {
      var _a;
      const pageMatch = inner.match(/ri:content-title="([^"]*)"/i);
      const page = (_a = pageMatch == null ? void 0 : pageMatch[1]) != null ? _a : "";
      return page ? `
![[${page}]]
` : "";
    }
  );
  s = s.replace(
    /<ac:structured-macro[^>]*\bac:name="jira"[^>]*>([\s\S]*?)<\/ac:structured-macro>/gi,
    (_m, inner) => {
      var _a, _b;
      const keyMatch = inner.match(/<ac:parameter[^>]*\bac:name="key"[^>]*>([\s\S]*?)<\/ac:parameter>/i);
      const key = (_b = (_a = keyMatch == null ? void 0 : keyMatch[1]) == null ? void 0 : _a.trim()) != null ? _b : "";
      return key ? `**${key}**` : "";
    }
  );
  s = s.replace(
    /<ac:structured-macro[^>]*\bac:name="anchor"[^>]*>([\s\S]*?)<\/ac:structured-macro>/gi,
    (_m, inner) => {
      var _a, _b;
      const nameMatch = inner.match(/<ac:parameter[^>]*\bac:name="0"[^>]*>([\s\S]*?)<\/ac:parameter>/i);
      const name = (_b = (_a = nameMatch == null ? void 0 : nameMatch[1]) == null ? void 0 : _a.trim()) != null ? _b : "";
      return name ? `<a id="${name}"></a>` : "";
    }
  );
  s = s.replace(
    /<ac:structured-macro[^>]*\bac:name="quote"[^>]*>([\s\S]*?)<\/ac:structured-macro>/gi,
    (_m, inner) => {
      const bodyMatch = inner.match(/<ac:rich-text-body[^>]*>([\s\S]*?)<\/ac:rich-text-body>/i);
      const body = bodyMatch ? bodyMatch[1] : inner;
      return `<blockquote>${body}</blockquote>`;
    }
  );
  s = s.replace(
    /<ac:structured-macro[^>]*\bac:name="divider"[^>]*(?:\/>|>[\s\S]*?<\/ac:structured-macro>)/gi,
    "\n<hr/>\n"
  );
  s = s.replace(
    /<ac:structured-macro[^>]*\bac:name="widget"[^>]*>([\s\S]*?)<\/ac:structured-macro>/gi,
    (_m, inner) => {
      var _a, _b;
      const urlMatch = inner.match(/<ac:parameter[^>]*\bac:name="url"[^>]*>([\s\S]*?)<\/ac:parameter>/i);
      const url = (_b = (_a = urlMatch == null ? void 0 : urlMatch[1]) == null ? void 0 : _a.trim()) != null ? _b : "";
      return url ? `[Embedded content](${url})` : "";
    }
  );
  s = s.replace(
    /<ac:structured-macro[^>]*\bac:name="(?:children|pagetree|page-tree|recently-updated|activity-stream|livesearch|profile-picture|roadmap|chart|html|iframe|navitabs|create-from-template|blog-posts|contributors|contributors-summary|space-list|recently-updated-dashboard|details|details-summary)"[^>]*>[\s\S]*?<\/ac:structured-macro>/gi,
    ""
  );
  s = s.replace(
    /<ac:structured-macro[^>]*>([\s\S]*?)<\/ac:structured-macro>/gi,
    (_m, inner) => {
      const bodyMatch = inner.match(/<ac:rich-text-body[^>]*>([\s\S]*?)<\/ac:rich-text-body>/i);
      return bodyMatch ? bodyMatch[1] : "";
    }
  );
  s = s.replace(
    /<ac:link[^>]*>\s*<ri:user[^>]*\bri:username="([^"]*)"[^>]*\/?>\s*(?:<ac:link-body>[\s\S]*?<\/ac:link-body>)?\s*<\/ac:link>/gi,
    (_m, username) => `@${username}`
  );
  s = s.replace(
    /<ac:link[^>]*>\s*<ri:user[^>]*\bri:account-id="[^"]*"[^>]*\/?>\s*(?:<ac:link-body>([\s\S]*?)<\/ac:link-body>)?\s*<\/ac:link>/gi,
    (_m, body) => {
      const name = body == null ? void 0 : body.replace(/<[^>]+>/g, "").trim();
      return name ? `@${name}` : "@user";
    }
  );
  if (wikiLinks) {
    s = s.replace(
      /<ac:link[^>]*>\s*<ri:page[^>]*\bri:content-title="([^"]*)"[^>]*\/?>\s*(?:<ac:link-body>([\s\S]*?)<\/ac:link-body>)?\s*<\/ac:link>/gi,
      (_m, title) => `[[${title}]]`
    );
  } else {
    s = s.replace(
      /<ac:link[^>]*>\s*<ri:page[^>]*\bri:content-title="([^"]*)"[^>]*\/?>\s*(?:<ac:link-body>([\s\S]*?)<\/ac:link-body>)?\s*<\/ac:link>/gi,
      (_m, title, body) => (body == null ? void 0 : body.replace(/<[^>]+>/g, "")) || title
    );
  }
  s = s.replace(
    /<ac:link[^>]*>\s*<ri:url[^>]*\bri:value="([^"]*)"[^>]*\/?>\s*(?:<ac:link-body>([\s\S]*?)<\/ac:link-body>)?\s*<\/ac:link>/gi,
    (_m, url, body) => {
      const text = (body == null ? void 0 : body.replace(/<[^>]+>/g, "").trim()) || url;
      return `[${text}](${url})`;
    }
  );
  s = s.replace(
    /<ac:image[^>]*>\s*<ri:attachment[^>]*\bri:filename="([^"]*)"[^>]*\/?>\s*<\/ac:image>/gi,
    (_m, filename) => {
      var _a;
      const vaultPath = (_a = options.attachmentMap) == null ? void 0 : _a.get(filename);
      return vaultPath ? `![[${vaultPath}]]` : `![${filename}](${filename})`;
    }
  );
  s = s.replace(
    /<ac:image[^>]*>\s*<ri:url[^>]*\bri:value="([^"]*)"[^>]*\/?>\s*<\/ac:image>/gi,
    (_m, url) => `![](${url})`
  );
  s = s.replace(/<\/?(?:ac|ri):[^>]*>/gi, "");
  const parser = new DOMParser();
  const doc = parser.parseFromString(`<body>${s}</body>`, "text/html");
  return nodeToMd(doc.body).replace(/\n{3,}/g, "\n\n").trim();
}
function nodeToMd(node) {
  var _a, _b, _c, _d, _e, _f, _g, _h, _i;
  if (node.nodeType === Node.TEXT_NODE)
    return (_a = node.textContent) != null ? _a : "";
  if (node.nodeType !== Node.ELEMENT_NODE)
    return "";
  const el = node;
  const tag = el.tagName.toLowerCase();
  const kids = () => Array.from(el.childNodes).map(nodeToMd).join("");
  switch (tag) {
    case "h1":
      return `
# ${kids().trim()}
`;
    case "h2":
      return `
## ${kids().trim()}
`;
    case "h3":
      return `
### ${kids().trim()}
`;
    case "h4":
      return `
#### ${kids().trim()}
`;
    case "h5":
      return `
##### ${kids().trim()}
`;
    case "h6":
      return `
###### ${kids().trim()}
`;
    case "p":
      return `
${kids()}
`;
    case "br":
      return "\n";
    case "hr":
      return "\n---\n";
    case "strong":
    case "b":
      return `**${kids()}**`;
    case "em":
    case "i":
      return `*${kids()}*`;
    case "del":
    case "s":
      return `~~${kids()}~~`;
    case "code": {
      const text = kids();
      return text.includes("\n") ? `\`\`\`
${text}
\`\`\`` : `\`${text}\``;
    }
    case "pre": {
      const codeEl = el.querySelector("code");
      if (codeEl) {
        const lang = (_c = ((_b = codeEl.className.match(/language-(\w+)/)) != null ? _b : [])[1]) != null ? _c : "";
        return `
\`\`\`${lang}
${(_d = codeEl.textContent) != null ? _d : ""}
\`\`\`
`;
      }
      return `
\`\`\`
${(_e = el.textContent) != null ? _e : ""}
\`\`\`
`;
    }
    case "a": {
      const href = (_f = el.getAttribute("href")) != null ? _f : "";
      const text = kids().trim();
      return href ? `[${text}](${href})` : text;
    }
    case "img": {
      const src = (_g = el.getAttribute("src")) != null ? _g : "";
      const alt = (_h = el.getAttribute("alt")) != null ? _h : "";
      return `![${alt}](${src})`;
    }
    case "ul":
      return `
${renderList(el, false)}
`;
    case "ol":
      return `
${renderList(el, true)}
`;
    case "li":
      return kids();
    case "blockquote": {
      const cwType = el.getAttribute("data-cw-type");
      const cwTitle = (_i = el.getAttribute("data-cw-title")) != null ? _i : "";
      const cwCollapse = el.getAttribute("data-cw-collapse") === "true";
      const content = kids().trim();
      if (cwType) {
        const collapse = cwCollapse ? "-" : "";
        const lines = content.split("\n").map((l) => `> ${l}`).join("\n");
        return `
> [!${cwType}]${collapse} ${cwTitle}
${lines}
`;
      }
      return `
> ${content.replace(/\n/g, "\n> ")}
`;
    }
    case "table":
      return `
${renderTable(el)}
`;
    case "thead":
    case "tbody":
    case "tfoot":
    case "tr":
      return kids();
    default:
      return kids();
  }
}
function renderList(el, ordered) {
  const lines = [];
  let idx = 1;
  for (const child of Array.from(el.childNodes)) {
    if (child.nodeType !== Node.ELEMENT_NODE)
      continue;
    const tag = child.tagName.toLowerCase();
    if (tag !== "li")
      continue;
    const prefix = ordered ? `${idx++}. ` : "- ";
    const content = nodeToMd(child).trim().replace(/\n/g, "\n   ");
    lines.push(`${prefix}${content}`);
  }
  return lines.join("\n");
}
function renderTable(table) {
  const rows = Array.from(table.querySelectorAll("tr"));
  if (rows.length === 0)
    return "";
  const parsed = rows.map(
    (row) => Array.from(row.querySelectorAll("th, td")).map(
      (cell) => nodeToMd(cell).trim().replace(/\n+/g, " ").replace(/\|/g, "\\|")
    )
  );
  const colCount = Math.max(...parsed.map((r) => r.length));
  parsed.forEach((row) => {
    while (row.length < colCount)
      row.push("");
  });
  const sep = Array(colCount).fill("---");
  return [
    `| ${parsed[0].join(" | ")} |`,
    `| ${sep.join(" | ")} |`,
    ...parsed.slice(1).map((r) => `| ${r.join(" | ")} |`)
  ].join("\n");
}

// src/markdownBuilder.ts
function buildMarkdown(page, settings, existingContent, attachmentMap) {
  const frontmatter = buildFrontmatter(page, settings);
  const body = buildBody(page, settings, attachmentMap);
  const freshContent = `${frontmatter}
${body}

${SECTION_MARKER}
`;
  if (!existingContent)
    return freshContent;
  const markerIdx = existingContent.indexOf(SECTION_MARKER);
  if (markerIdx !== -1) {
    const userNotes = existingContent.slice(markerIdx + SECTION_MARKER.length);
    return `${frontmatter}
${body}

${SECTION_MARKER}${userNotes}`;
  }
  return settings.missingMarker === "skip" ? existingContent : freshContent;
}
function buildFrontmatter(page, settings) {
  var _a, _b, _c, _d, _e, _f, _g, _h, _i, _j, _k, _l, _m, _n, _o, _p, _q, _r, _s, _t, _u, _v, _w, _x;
  const domain = settings.domain.replace(/\/$/, "");
  const webui = (_b = (_a = page._links) == null ? void 0 : _a.webui) != null ? _b : "";
  const url = webui.startsWith("http") ? webui : `${domain}${webui}`;
  const labels = (_f = (_e = (_d = (_c = page.metadata) == null ? void 0 : _c.labels) == null ? void 0 : _d.results) == null ? void 0 : _e.map((l) => l.name)) != null ? _f : [];
  const parent = (_g = page.ancestors) == null ? void 0 : _g[page.ancestors.length - 1];
  const author = (_m = (_l = (_i = (_h = page.history) == null ? void 0 : _h.createdBy) == null ? void 0 : _i.displayName) != null ? _l : (_k = (_j = page.history) == null ? void 0 : _j.createdBy) == null ? void 0 : _k.username) != null ? _m : "";
  const created = yamlDate((_o = (_n = page.history) == null ? void 0 : _n.createdDate) != null ? _o : "");
  const updated = yamlDate((_q = (_p = page.version) == null ? void 0 : _p.when) != null ? _q : "");
  const lines = [
    "---",
    `confluence_id: ${yamlString(page.id)}`,
    `confluence_url: ${yamlString(url)}`,
    `title: ${yamlString(page.title)}`,
    `space: ${yamlString((_s = (_r = page.space) == null ? void 0 : _r.key) != null ? _s : "")}`,
    `space_name: ${yamlString((_u = (_t = page.space) == null ? void 0 : _t.name) != null ? _u : "")}`,
    `author: ${yamlString(author)}`,
    `created: "${created}"`,
    `updated: "${updated}"`,
    `version: ${(_w = (_v = page.version) == null ? void 0 : _v.number) != null ? _w : 0}`
  ];
  if (labels.length > 0) {
    lines.push("labels:");
    labels.forEach((l) => lines.push(`  - ${yamlString(l)}`));
  } else {
    lines.push("labels: []");
  }
  if (parent) {
    lines.push(`parent: "[[${parent.id}_${slugify(parent.title)}]]"`);
  }
  for (const mapping of (_x = settings.fieldMappings) != null ? _x : []) {
    const value = resolvePath(page, mapping.sourcePath);
    if (value !== void 0 && value !== null) {
      const serialized = Array.isArray(value) ? value.map((v) => String(v)) : String(value);
      if (Array.isArray(serialized)) {
        lines.push(`${mapping.frontmatterKey}:`);
        serialized.forEach((v) => lines.push(`  - ${yamlString(v)}`));
      } else {
        lines.push(`${mapping.frontmatterKey}: ${yamlString(serialized)}`);
      }
    }
  }
  lines.push("---");
  return lines.join("\n");
}
function buildBody(page, settings, attachmentMap) {
  var _a, _b, _c;
  let body = storageToMarkdown((_c = (_b = (_a = page.body) == null ? void 0 : _a.storage) == null ? void 0 : _b.value) != null ? _c : "", {
    wikiLinks: settings.wikiLinks,
    attachmentMap
  });
  if (settings.maxBodyLength > 0 && body.length > settings.maxBodyLength) {
    body = body.slice(0, settings.maxBodyLength) + "\n\n\u2026(truncated)";
  }
  return body;
}
function resolvePath(obj, path) {
  return path.split(".").reduce((cur, key) => {
    if (cur !== null && typeof cur === "object") {
      return cur[key];
    }
    return void 0;
  }, obj);
}

// src/settings.ts
var import_obsidian5 = require("obsidian");

// src/cqlProfileModal.ts
var import_obsidian4 = require("obsidian");
var CqlProfileModal = class extends import_obsidian4.Modal {
  constructor(app, profile, onSave) {
    super(app);
    this.profile = { ...profile };
    this.onSave = onSave;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    const isNew = !this.profile.id;
    contentEl.createEl("h2", { text: isNew ? t("modal.newProfile") : t("modal.editProfile") });
    new import_obsidian4.Setting(contentEl).setName(t("modal.profileName")).addText(
      (text) => text.setValue(this.profile.name).onChange((v) => {
        this.profile.name = v;
      })
    );
    new import_obsidian4.Setting(contentEl).setName(t("modal.cql")).addTextArea((area) => {
      area.setValue(this.profile.cql).onChange((v) => {
        this.profile.cql = v;
      });
      area.inputEl.rows = 4;
      area.inputEl.addClass("cw-textarea");
    });
    new import_obsidian4.Setting(contentEl).setName(t("modal.folder")).setDesc(t("modal.folder.desc")).addText(
      (text) => text.setPlaceholder("Confluence").setValue(this.profile.folder).onChange((v) => {
        this.profile.folder = v;
      })
    );
    new import_obsidian4.Setting(contentEl).setName(t("modal.maxPages")).addText(
      (text) => text.setValue(String(this.profile.maxPages)).onChange((v) => {
        this.profile.maxPages = Math.max(1, parseInt(v) || 50);
      })
    );
    new import_obsidian4.Setting(contentEl).addButton(
      (btn) => btn.setButtonText(t("modal.save")).setCta().onClick(() => {
        if (isNew)
          this.profile.id = Date.now().toString();
        this.onSave(this.profile);
        this.close();
      })
    ).addButton(
      (btn) => btn.setButtonText(t("modal.cancel")).onClick(() => this.close())
    );
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/settings.ts
var ConfluenceWeaverSettingTab = class extends import_obsidian5.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: t("setting.title") });
    new import_obsidian5.Setting(containerEl).setName(t("setting.language")).setDesc(t("setting.language.desc")).addDropdown(
      (drop) => drop.addOption("auto", t("setting.language.auto")).addOption("en", t("setting.language.en")).addOption("ko", t("setting.language.ko")).addOption("ja", t("setting.language.ja")).addOption("zh", t("setting.language.zh")).setValue(this.plugin.settings.language).onChange(async (v) => {
        this.plugin.settings.language = v;
        await this.plugin.saveSettings();
        setLocale(this.plugin.settings.language);
        this.display();
      })
    );
    containerEl.createEl("h3", { text: t("setting.connection") });
    new import_obsidian5.Setting(containerEl).setName(t("setting.domain")).setDesc(t("setting.domain.desc")).addText(
      (text) => text.setPlaceholder("https://mycompany.atlassian.net/wiki").setValue(this.plugin.settings.domain).onChange(async (v) => {
        this.plugin.settings.domain = v.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian5.Setting(containerEl).setName(t("setting.authMode")).addDropdown(
      (drop) => drop.addOption("basic", t("setting.authMode.basic")).addOption("bearer", t("setting.authMode.bearer")).setValue(this.plugin.settings.authMode).onChange(async (v) => {
        this.plugin.settings.authMode = v;
        await this.plugin.saveSettings();
        this.display();
      })
    );
    if (this.plugin.settings.authMode === "basic") {
      new import_obsidian5.Setting(containerEl).setName(t("setting.email")).setDesc(t("setting.email.desc")).addText(
        (text) => text.setValue(this.plugin.settings.email).onChange(async (v) => {
          this.plugin.settings.email = v.trim();
          await this.plugin.saveSettings();
        })
      );
    }
    new import_obsidian5.Setting(containerEl).setName(t("setting.token")).setDesc(t("setting.token.desc")).addText((text) => {
      text.setValue(this.plugin.settings.token).onChange(async (v) => {
        this.plugin.settings.token = v.trim();
        await this.plugin.saveSettings();
      });
      text.inputEl.type = "password";
    });
    new import_obsidian5.Setting(containerEl).addButton(
      (btn) => btn.setButtonText(t("setting.testConnection")).onClick(async () => {
        new import_obsidian5.Notice(t("notice.connecting"));
        try {
          await new ConfluenceClient(this.plugin.settings).testConnection();
          new import_obsidian5.Notice(t("notice.connected"));
        } catch (e) {
          new import_obsidian5.Notice(`${t("notice.connectFailed")}${e.message}`);
        }
      })
    );
    containerEl.createEl("h3", { text: t("setting.profiles") });
    for (const profile of this.plugin.settings.profiles) {
      const setting = new import_obsidian5.Setting(containerEl).setName(profile.name || "(unnamed)").setDesc(profile.cql);
      setting.addToggle(
        (toggle) => toggle.setValue(profile.enabled).onChange(async (v) => {
          profile.enabled = v;
          await this.plugin.saveSettings();
        })
      );
      setting.addButton(
        (btn) => btn.setButtonText(t("setting.editProfile")).onClick(
          () => new CqlProfileModal(this.app, profile, async (updated) => {
            const idx = this.plugin.settings.profiles.findIndex((p) => p.id === updated.id);
            if (idx !== -1)
              this.plugin.settings.profiles[idx] = updated;
            await this.plugin.saveSettings();
            this.display();
          }).open()
        )
      );
      setting.addButton(
        (btn) => btn.setButtonText(t("setting.deleteProfile")).setWarning().onClick(async () => {
          this.plugin.settings.profiles = this.plugin.settings.profiles.filter(
            (p) => p.id !== profile.id
          );
          await this.plugin.saveSettings();
          this.display();
        })
      );
    }
    new import_obsidian5.Setting(containerEl).addButton(
      (btn) => btn.setButtonText(t("setting.addProfile")).onClick(() => {
        const blank = {
          id: "",
          name: "",
          cql: "",
          folder: "Confluence",
          maxPages: 50,
          enabled: true
        };
        new CqlProfileModal(this.app, blank, async (created) => {
          this.plugin.settings.profiles.push(created);
          await this.plugin.saveSettings();
          this.display();
        }).open();
      })
    );
    containerEl.createEl("h3", { text: t("setting.sync") });
    new import_obsidian5.Setting(containerEl).setName(t("setting.syncOnStartup")).setDesc(t("setting.syncOnStartup.desc")).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.syncOnStartup).onChange(async (v) => {
        this.plugin.settings.syncOnStartup = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian5.Setting(containerEl).setName(t("setting.syncInterval")).setDesc(t("setting.syncInterval.desc")).addText(
      (text) => text.setValue(String(this.plugin.settings.syncInterval)).onChange(async (v) => {
        this.plugin.settings.syncInterval = Math.min(1440, Math.max(0, parseInt(v) || 0));
        await this.plugin.saveSettings();
        this.plugin.scheduler.restart();
      })
    );
    new import_obsidian5.Setting(containerEl).setName(t("setting.missingMarker")).setDesc(t("setting.missingMarker.desc")).addDropdown(
      (drop) => drop.addOption("overwrite", t("setting.missingMarker.overwrite")).addOption("skip", t("setting.missingMarker.skip")).setValue(this.plugin.settings.missingMarker).onChange(async (v) => {
        this.plugin.settings.missingMarker = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian5.Setting(containerEl).setName(t("setting.folderHierarchy")).setDesc(t("setting.folderHierarchy.desc")).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.folderHierarchy).onChange(async (v) => {
        this.plugin.settings.folderHierarchy = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian5.Setting(containerEl).setName(t("setting.wikiLinks")).setDesc(t("setting.wikiLinks.desc")).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.wikiLinks).onChange(async (v) => {
        this.plugin.settings.wikiLinks = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian5.Setting(containerEl).setName(t("setting.downloadAttachments")).setDesc(t("setting.downloadAttachments.desc")).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.downloadAttachments).onChange(async (v) => {
        this.plugin.settings.downloadAttachments = v;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: t("setting.advanced") });
    new import_obsidian5.Setting(containerEl).setName(t("setting.maxBodyLength")).setDesc(t("setting.maxBodyLength.desc")).addText(
      (text) => text.setValue(String(this.plugin.settings.maxBodyLength)).onChange(async (v) => {
        this.plugin.settings.maxBodyLength = Math.max(0, parseInt(v) || 0);
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian5.Setting(containerEl).setName(t("setting.fieldMappings")).setDesc(t("setting.fieldMappings.desc")).addTextArea((area) => {
      const toText = () => {
        var _a;
        return ((_a = this.plugin.settings.fieldMappings) != null ? _a : []).map((m) => `${m.sourcePath} \u2192 ${m.frontmatterKey}`).join("\n");
      };
      area.setValue(toText()).onChange(async (raw) => {
        this.plugin.settings.fieldMappings = raw.split("\n").map((line) => line.trim()).filter((line) => line.includes("\u2192") || line.includes("->")).map((line) => {
          const [src, tgt] = line.split(/→|->/).map((s) => s.trim());
          return { sourcePath: src, frontmatterKey: tgt };
        }).filter((m) => m.sourcePath && m.frontmatterKey);
        await this.plugin.saveSettings();
      });
      area.inputEl.rows = 5;
      area.inputEl.addClass("cw-textarea");
      area.inputEl.addClass("cw-textarea-mono");
    });
  }
};

// src/syncScheduler.ts
var SyncScheduler = class {
  constructor(plugin) {
    this.plugin = plugin;
    this.intervalId = null;
  }
  start() {
    if (this.plugin.settings.syncOnStartup) {
      window.setTimeout(() => this.plugin.syncPages(false), 3e3);
    }
    this.scheduleInterval();
  }
  restart() {
    this.stop();
    this.scheduleInterval();
  }
  stop() {
    if (this.intervalId !== null) {
      window.clearInterval(this.intervalId);
      this.intervalId = null;
    }
  }
  scheduleInterval() {
    const minutes = this.plugin.settings.syncInterval;
    if (minutes > 0) {
      this.intervalId = window.setInterval(
        () => this.plugin.syncPages(false),
        minutes * 60 * 1e3
      );
    }
  }
};

// src/syncLogView.ts
var import_obsidian6 = require("obsidian");
var VIEW_TYPE_SYNC_LOG = "confluence-weaver-sync-log";
var SyncLogView = class extends import_obsidian6.ItemView {
  constructor(leaf) {
    super(leaf);
    this.stats = [];
  }
  getViewType() {
    return VIEW_TYPE_SYNC_LOG;
  }
  getDisplayText() {
    return t("log.title");
  }
  getIcon() {
    return "refresh-cw";
  }
  async onOpen() {
    this.render();
  }
  async onClose() {
  }
  setStats(stats) {
    this.stats = stats;
    this.render();
  }
  render() {
    const root = this.containerEl.children[1];
    root.empty();
    root.createEl("h4", { text: t("log.title"), cls: "cw-log-heading" });
    if (this.stats.length === 0) {
      root.createEl("p", { text: t("log.noStats"), cls: "cw-log-empty" });
      return;
    }
    for (const stat of this.stats) {
      const section = root.createEl("div", { cls: "cw-log-section" });
      section.createEl("h5", { text: stat.profileName, cls: "cw-log-profile" });
      const table = section.createEl("table", { cls: "cw-log-table" });
      const addRow = (label, value) => {
        const tr = table.createEl("tr");
        tr.createEl("td", { text: label, cls: "cw-log-label" });
        tr.createEl("td", { text: String(value), cls: "cw-log-value" });
      };
      addRow(t("log.created"), stat.created);
      addRow(t("log.updated"), stat.updated);
      addRow(t("log.skipped"), stat.skipped);
      addRow(t("log.errors"), stat.errors);
      addRow(t("log.lastSync"), stat.lastSync ? stat.lastSync.replace("T", " ").slice(0, 19) : t("log.never"));
    }
  }
};

// src/main.ts
var DEFAULT_SETTINGS = {
  domain: "",
  authMode: "basic",
  email: "",
  token: "",
  profiles: [],
  syncOnStartup: false,
  syncInterval: 0,
  missingMarker: "overwrite",
  folderHierarchy: false,
  maxBodyLength: 0,
  wikiLinks: true,
  fieldMappings: [],
  downloadAttachments: false,
  language: "auto"
};
var ConfluenceWeaverPlugin = class extends import_obsidian7.Plugin {
  constructor() {
    super(...arguments);
    this.settings = { ...DEFAULT_SETTINGS };
    this.scheduler = new SyncScheduler(this);
    this.syncStats = [];
  }
  async onload() {
    await this.loadSettings();
    setLocale(this.settings.language);
    this.registerView(VIEW_TYPE_SYNC_LOG, (leaf) => new SyncLogView(leaf));
    this.addCommand({
      id: "sync-pages",
      name: t("cmd.sync"),
      callback: () => this.syncPages(false)
    });
    this.addCommand({
      id: "force-sync-pages",
      name: t("cmd.forceSync"),
      callback: () => this.syncPages(true)
    });
    this.addCommand({
      id: "open-sync-log",
      name: t("cmd.openLog"),
      callback: () => this.openSyncLog()
    });
    this.addCommand({
      id: "link-jira-weaver-pages",
      name: t("cmd.linkJira"),
      callback: () => this.runJiraWeaverBridge()
    });
    this.addCommand({
      id: "fetch-page-by-url",
      name: t("cmd.fetchByUrl"),
      callback: () => new UrlPageModal(this.app, this).open()
    });
    this.addSettingTab(new ConfluenceWeaverSettingTab(this.app, this));
    this.scheduler.start();
  }
  onunload() {
    this.scheduler.stop();
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async syncPages(forceOverwrite) {
    var _a, _b;
    const active = this.settings.profiles.filter((p) => p.enabled);
    if (active.length === 0) {
      new import_obsidian7.Notice("Confluence Weaver: No enabled CQL profiles.");
      return;
    }
    if (!this.settings.domain || !this.settings.token) {
      new import_obsidian7.Notice("Confluence Weaver: Configure domain and token in settings first.");
      return;
    }
    new import_obsidian7.Notice(t("notice.syncing"));
    const client = new ConfluenceClient(this.settings);
    const fm = new FileManager(this.app);
    const allStats = [];
    for (const profile of active) {
      const stats = {
        profileId: profile.id,
        profileName: profile.name,
        created: 0,
        updated: 0,
        skipped: 0,
        errors: 0,
        lastSync: new Date().toISOString()
      };
      try {
        const summaries = await client.searchCQL(profile.cql, profile.maxPages);
        for (const summary of summaries) {
          try {
            const page = await client.getPage(summary.id);
            const filePath = fm.resolveFilePath(page, profile.folder, this.settings.folderHierarchy);
            const existing = await fm.readFile(filePath);
            if (!forceOverwrite && existing) {
              const versionMatch = existing.match(/^version:\s*(\d+)/m);
              if (versionMatch && parseInt(versionMatch[1]) >= ((_b = (_a = page.version) == null ? void 0 : _a.number) != null ? _b : 0)) {
                stats.skipped++;
                continue;
              }
            }
            const attachmentMap = this.settings.downloadAttachments ? await this.downloadPageAttachments(page, profile.folder, client, fm) : void 0;
            const content = buildMarkdown(
              page,
              this.settings,
              forceOverwrite ? void 0 : existing != null ? existing : void 0,
              attachmentMap
            );
            if (existing && content === existing) {
              stats.skipped++;
              continue;
            }
            const result = await fm.writeFile(filePath, content);
            result === "created" ? stats.created++ : stats.updated++;
          } catch (e) {
            console.error(`Confluence Weaver: page ${summary.id}`, e);
            stats.errors++;
          }
        }
      } catch (e) {
        console.error(`Confluence Weaver: profile "${profile.name}"`, e);
        new import_obsidian7.Notice(`${t("notice.syncFailed")}${e.message}`);
        stats.errors++;
      }
      allStats.push(stats);
    }
    this.syncStats = allStats;
    this.refreshLogView();
    new import_obsidian7.Notice(t("notice.syncDone"));
  }
  refreshLogView() {
    for (const leaf of this.app.workspace.getLeavesOfType(VIEW_TYPE_SYNC_LOG)) {
      if (leaf.view instanceof SyncLogView)
        leaf.view.setStats(this.syncStats);
    }
  }
  async fetchByUrl(url, folder, includeChildren, allDescendants, maxPages) {
    if (!this.settings.domain || !this.settings.token) {
      new import_obsidian7.Notice("Confluence Weaver: Configure domain and token in settings first.");
      return;
    }
    const client = new ConfluenceClient(this.settings);
    const fm = new FileManager(this.app);
    let rootId = client.parsePageId(url);
    if (!rootId) {
      rootId = await client.resolveDisplayUrl(url);
    }
    if (!rootId) {
      new import_obsidian7.Notice(t("notice.url.invalidUrl"));
      return;
    }
    new import_obsidian7.Notice(t("notice.url.fetching"));
    try {
      const idsToFetch = [rootId];
      if (includeChildren) {
        if (allDescendants) {
          const desc = await client.collectDescendantIds(rootId, maxPages - 1);
          idsToFetch.push(...desc);
        } else {
          const children = await client.getChildPageIds(rootId);
          idsToFetch.push(...children.slice(0, maxPages - 1));
        }
      }
      let created = 0;
      let updated = 0;
      for (const id of idsToFetch) {
        try {
          const page = await client.getPage(id);
          const filePath = fm.resolveFilePath(page, folder, this.settings.folderHierarchy);
          const existing = await fm.readFile(filePath);
          const attachmentMap = this.settings.downloadAttachments ? await this.downloadPageAttachments(page, folder, client, fm) : void 0;
          const content = buildMarkdown(page, this.settings, existing != null ? existing : void 0, attachmentMap);
          if (existing && content === existing)
            continue;
          const result = await fm.writeFile(filePath, content);
          result === "created" ? created++ : updated++;
        } catch (e) {
          console.error(`Confluence Weaver: fetch page ${id}`, e);
        }
      }
      new import_obsidian7.Notice(
        t("notice.url.done").replace("{created}", String(created)).replace("{updated}", String(updated))
      );
    } catch (e) {
      new import_obsidian7.Notice(`${t("notice.url.failed")}${e.message}`);
    }
  }
  /**
   * Download image attachments for a page and return a filename→vaultPath map.
   * Skips files that are already up-to-date (existing binary untouched).
   */
  async downloadPageAttachments(page, baseFolder, client, fm) {
    const map = /* @__PURE__ */ new Map();
    try {
      const attachments = await client.getPageAttachments(page.id);
      for (const att of attachments) {
        const safeName = att.title.replace(/[\\/:*?"<>|]/g, "_");
        const vaultPath = baseFolder ? `${baseFolder}/_attachments/${page.id}/${safeName}` : `_attachments/${page.id}/${safeName}`;
        try {
          const data = await client.downloadAttachment(att._links.download);
          await fm.writeBinaryFile(vaultPath, data);
          map.set(att.title, vaultPath);
        } catch (e) {
          console.error(`Confluence Weaver: attachment ${att.title}`, e);
        }
      }
    } catch (e) {
      console.error(`Confluence Weaver: getPageAttachments ${page.id}`, e);
    }
    return map;
  }
  async runJiraWeaverBridge() {
    new import_obsidian7.Notice(t("notice.linkJira"));
    try {
      const count = await linkJiraPages(this.app);
      new import_obsidian7.Notice(t("notice.linkJiraDone").replace("{count}", String(count)));
    } catch (e) {
      new import_obsidian7.Notice(`${t("notice.linkJiraFailed")}${e.message}`);
    }
  }
  async openSyncLog() {
    const existing = this.app.workspace.getLeavesOfType(VIEW_TYPE_SYNC_LOG);
    if (existing.length > 0) {
      this.app.workspace.revealLeaf(existing[0]);
      return;
    }
    const leaf = this.app.workspace.getRightLeaf(false);
    if (leaf) {
      await leaf.setViewState({ type: VIEW_TYPE_SYNC_LOG, active: true });
      this.app.workspace.revealLeaf(leaf);
    }
  }
};
