/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Source: https://github.com/hyukjin78/confluence-weaver
*/
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ConfluenceWeaverPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");

// src/jiraWeaverBridge.ts
async function buildUrlMap(app) {
  const map = /* @__PURE__ */ new Map();
  const files = app.vault.getMarkdownFiles();
  for (const file of files) {
    const content = await app.vault.read(file);
    const urlMatch = content.match(/^confluence_url:\s*["']?([^\s"'\n]+)["']?/m);
    if (!urlMatch)
      continue;
    const rawUrl = urlMatch[1].trim();
    const normalizedUrl = rawUrl.replace(/[?#].*$/, "").replace(/\/$/, "");
    const wikiName = file.path.replace(/\.md$/, "");
    map.set(normalizedUrl, wikiName);
  }
  return map;
}
function isJiraWeaverFile(content) {
  return /^jira_id:/m.test(content);
}
function replaceConfluenceUrls(body, urlMap) {
  let count = 0;
  let result = body;
  for (const [url, wikiName] of urlMap) {
    const escaped = url.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    const mdLinkRe = new RegExp(`\\[([^\\]]+)\\]\\(${escaped}[^)]*\\)`, "g");
    result = result.replace(mdLinkRe, (_m, text) => {
      count++;
      return `[[${wikiName}|${text}]]`;
    });
    const bareRe = new RegExp(`(?<!\\()${escaped}(?:[^\\s)\\]"]*)?`, "g");
    result = result.replace(bareRe, () => {
      count++;
      return `[[${wikiName}]]`;
    });
  }
  return { result, count };
}
async function linkJiraPages(app) {
  const urlMap = await buildUrlMap(app);
  if (urlMap.size === 0)
    return 0;
  const files = app.vault.getMarkdownFiles();
  let totalReplaced = 0;
  for (const file of files) {
    const content = await app.vault.read(file);
    if (!isJiraWeaverFile(content))
      continue;
    const fmEnd = findFrontmatterEnd(content);
    const frontmatter = content.slice(0, fmEnd);
    const body = content.slice(fmEnd);
    const { result, count } = replaceConfluenceUrls(body, urlMap);
    if (count === 0)
      continue;
    await app.vault.modify(file, frontmatter + result);
    totalReplaced += count;
  }
  return totalReplaced;
}
function findFrontmatterEnd(content) {
  if (!content.startsWith("---"))
    return 0;
  const rest = content.slice(3);
  const closeIdx = rest.search(/\n---\s*\n/);
  if (closeIdx === -1)
    return 0;
  return closeIdx + 3 + "\n---\n".length;
}

// src/confluenceClient.ts
var ConfluenceClient = class {
  constructor(settings) {
    this.settings = settings;
  }
  get baseUrl() {
    return this.settings.domain.replace(/\/$/, "");
  }
  authHeader() {
    if (this.settings.authMode === "basic") {
      const creds = btoa(`${this.settings.email}:${this.settings.token}`);
      return `Basic ${creds}`;
    }
    return `Bearer ${this.settings.token}`;
  }
  async get(path) {
    const url = `${this.baseUrl}${path}`;
    const resp = await fetch(url, {
      method: "GET",
      headers: {
        Authorization: this.authHeader(),
        "Content-Type": "application/json",
        Accept: "application/json"
      }
    });
    if (!resp.ok) {
      const body = await resp.text().catch(() => "");
      const hint = body.slice(0, 200);
      throw new Error(`${resp.status} ${resp.statusText}${hint ? ": " + hint : ""}`);
    }
    return resp.json();
  }
  async testConnection() {
    await this.get("/rest/api/space?limit=1");
  }
  async searchCQL(cql, limit = 50) {
    var _a;
    const data = await this.get(
      `/rest/api/content/search?cql=${encodeURIComponent(cql)}&limit=${limit}&expand=version,space,ancestors`
    );
    return (_a = data.results) != null ? _a : [];
  }
  async getPage(id) {
    return this.get(
      `/rest/api/content/${id}?expand=body.storage,version,ancestors,space,metadata.labels,history`
    );
  }
  async getPageProperties(id) {
    var _a;
    const data = await this.get(
      `/rest/api/content/${id}/property?limit=50`
    );
    return Object.fromEntries(((_a = data.results) != null ? _a : []).map((p) => [p.key, p.value]));
  }
};

// src/fileManager.ts
var import_obsidian = require("obsidian");

// src/fieldResolver.ts
function yamlString(value) {
  const collapsed = value.replace(/\r?\n/g, " ").replace(/\r/g, " ");
  if (/[:#\[\]{}|>&*!,'"%@`]/.test(collapsed) || collapsed.trim() !== collapsed || collapsed === "") {
    return `"${collapsed.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
  }
  return collapsed;
}
function yamlDate(isoString) {
  return (isoString || "").split("T")[0];
}
function slugify(text) {
  return text.toLowerCase().replace(/[^\w\s-]/g, "").replace(/[\s_]+/g, "-").replace(/^-+|-+$/g, "");
}

// src/fileManager.ts
var FileManager = class {
  constructor(app) {
    this.app = app;
  }
  async ensureFolder(folderPath) {
    var _a;
    const path = (0, import_obsidian.normalizePath)(folderPath);
    if (!path || path === ".")
      return;
    const existing = this.app.vault.getAbstractFileByPath(path);
    if (existing instanceof import_obsidian.TFolder)
      return;
    const parts = path.split("/");
    if (parts.length > 1) {
      await this.ensureFolder(parts.slice(0, -1).join("/"));
    }
    const after = this.app.vault.getAbstractFileByPath(path);
    if (!after) {
      try {
        await this.app.vault.createFolder(path);
      } catch (e) {
        if (!((_a = e.message) == null ? void 0 : _a.includes("already exists")))
          throw e;
      }
    }
  }
  async readFile(path) {
    const file = this.app.vault.getAbstractFileByPath((0, import_obsidian.normalizePath)(path));
    return file instanceof import_obsidian.TFile ? this.app.vault.read(file) : null;
  }
  async writeFile(path, content) {
    const normalized = (0, import_obsidian.normalizePath)(path);
    const existing = this.app.vault.getAbstractFileByPath(normalized);
    if (existing instanceof import_obsidian.TFile) {
      await this.app.vault.modify(existing, content);
      return "updated";
    }
    const parts = normalized.split("/");
    if (parts.length > 1) {
      await this.ensureFolder(parts.slice(0, -1).join("/"));
    }
    await this.app.vault.create(normalized, content);
    return "created";
  }
  resolveFilePath(page, baseFolder, folderHierarchy) {
    var _a;
    const fileName = `${page.id}_${slugify(page.title)}.md`;
    if (folderHierarchy && ((_a = page.ancestors) == null ? void 0 : _a.length) > 0) {
      const ancestorPath = page.ancestors.map((a) => slugify(a.title)).join("/");
      const folder = baseFolder ? `${baseFolder}/${ancestorPath}` : ancestorPath;
      return (0, import_obsidian.normalizePath)(`${folder}/${fileName}`);
    }
    return baseFolder ? (0, import_obsidian.normalizePath)(`${baseFolder}/${fileName}`) : (0, import_obsidian.normalizePath)(fileName);
  }
};

// src/types.ts
var SECTION_MARKER = "[confluence-weaver section end]";

// src/storageToMarkdown.ts
function storageToMarkdown(html, options = {}) {
  const { wikiLinks = true } = options;
  let s = html;
  s = s.replace(
    /<ac:task-list[^>]*>([\s\S]*?)<\/ac:task-list>/gi,
    (_m, inner) => {
      var _a, _b, _c;
      const tasks = [];
      const taskRe = /<ac:task[^>]*>([\s\S]*?)<\/ac:task>/gi;
      let tm;
      while ((tm = taskRe.exec(inner)) !== null) {
        const taskInner = tm[1];
        const statusMatch = taskInner.match(/<ac:task-status[^>]*>([\s\S]*?)<\/ac:task-status>/i);
        const bodyMatch = taskInner.match(/<ac:task-body[^>]*>([\s\S]*?)<\/ac:task-body>/i);
        const done = ((_a = statusMatch == null ? void 0 : statusMatch[1]) == null ? void 0 : _a.trim().toLowerCase()) === "complete";
        const body = (_c = (_b = bodyMatch == null ? void 0 : bodyMatch[1]) == null ? void 0 : _b.replace(/<[^>]+>/g, "").trim()) != null ? _c : "";
        tasks.push(`- [${done ? "x" : " "}] ${body}`);
      }
      return tasks.join("\n") + "\n";
    }
  );
  s = s.replace(
    /<ac:status\b[^>]*\bac:title="([^"]*)"[^>]*\/?>/gi,
    (_m, title) => `**${title}**`
  );
  s = s.replace(/<ac:emoticon[^>]*\/>/gi, "");
  s = s.replace(
    /<ac:structured-macro[^>]*\bac:name="toc"[^>]*>[\s\S]*?<\/ac:structured-macro>/gi,
    ""
  );
  s = s.replace(
    /<ac:structured-macro[^>]*\bac:name="code"[^>]*>([\s\S]*?)<\/ac:structured-macro>/gi,
    (_m, inner) => {
      var _a, _b;
      const langMatch = inner.match(/<ac:parameter[^>]*\bac:name="language"[^>]*>([\s\S]*?)<\/ac:parameter>/i);
      const lang = langMatch ? langMatch[1].trim() : "";
      const cdataMatch = inner.match(/<ac:plain-text-body[^>]*><!\[CDATA\[([\s\S]*?)\]\]><\/ac:plain-text-body>/i);
      const textMatch = inner.match(/<ac:plain-text-body[^>]*>([\s\S]*?)<\/ac:plain-text-body>/i);
      const code = (_b = (_a = cdataMatch != null ? cdataMatch : textMatch) == null ? void 0 : _a[1]) != null ? _b : "";
      return `
\`\`\`${lang}
${code}
\`\`\`
`;
    }
  );
  s = s.replace(
    /<ac:structured-macro[^>]*\bac:name="(info|note|warning|tip)"[^>]*>([\s\S]*?)<\/ac:structured-macro>/gi,
    (_m, type, inner) => {
      const bodyMatch = inner.match(/<ac:rich-text-body[^>]*>([\s\S]*?)<\/ac:rich-text-body>/i);
      const body = bodyMatch ? bodyMatch[1] : inner;
      return `
> **${type.toUpperCase()}**: ${body.trim()}
`;
    }
  );
  s = s.replace(
    /<ac:structured-macro[^>]*>([\s\S]*?)<\/ac:structured-macro>/gi,
    (_m, inner) => {
      const bodyMatch = inner.match(/<ac:rich-text-body[^>]*>([\s\S]*?)<\/ac:rich-text-body>/i);
      return bodyMatch ? bodyMatch[1] : "";
    }
  );
  if (wikiLinks) {
    s = s.replace(
      /<ac:link[^>]*>\s*<ri:page[^>]*\bri:content-title="([^"]*)"[^>]*\/?>\s*(?:<ac:link-body>([\s\S]*?)<\/ac:link-body>)?\s*<\/ac:link>/gi,
      (_m, title) => `[[${title}]]`
    );
  } else {
    s = s.replace(
      /<ac:link[^>]*>\s*<ri:page[^>]*\bri:content-title="([^"]*)"[^>]*\/?>\s*(?:<ac:link-body>([\s\S]*?)<\/ac:link-body>)?\s*<\/ac:link>/gi,
      (_m, title, body) => (body == null ? void 0 : body.replace(/<[^>]+>/g, "")) || title
    );
  }
  s = s.replace(
    /<ac:link[^>]*>\s*<ri:url[^>]*\bri:value="([^"]*)"[^>]*\/?>\s*(?:<ac:link-body>([\s\S]*?)<\/ac:link-body>)?\s*<\/ac:link>/gi,
    (_m, url, body) => {
      const text = (body == null ? void 0 : body.replace(/<[^>]+>/g, "").trim()) || url;
      return `[${text}](${url})`;
    }
  );
  s = s.replace(
    /<ac:image[^>]*>\s*<ri:attachment[^>]*\bri:filename="([^"]*)"[^>]*\/?>\s*<\/ac:image>/gi,
    (_m, filename) => `![${filename}](${filename})`
  );
  s = s.replace(
    /<ac:image[^>]*>\s*<ri:url[^>]*\bri:value="([^"]*)"[^>]*\/?>\s*<\/ac:image>/gi,
    (_m, url) => `![](${url})`
  );
  s = s.replace(/<\/?(?:ac|ri):[^>]*>/gi, "");
  const parser = new DOMParser();
  const doc = parser.parseFromString(`<body>${s}</body>`, "text/html");
  return nodeToMd(doc.body).replace(/\n{3,}/g, "\n\n").trim();
}
function nodeToMd(node) {
  var _a, _b, _c, _d, _e, _f, _g, _h;
  if (node.nodeType === Node.TEXT_NODE) {
    return (_a = node.textContent) != null ? _a : "";
  }
  if (node.nodeType !== Node.ELEMENT_NODE)
    return "";
  const el = node;
  const tag = el.tagName.toLowerCase();
  const kids = () => Array.from(el.childNodes).map(nodeToMd).join("");
  switch (tag) {
    case "h1":
      return `
# ${kids().trim()}
`;
    case "h2":
      return `
## ${kids().trim()}
`;
    case "h3":
      return `
### ${kids().trim()}
`;
    case "h4":
      return `
#### ${kids().trim()}
`;
    case "h5":
      return `
##### ${kids().trim()}
`;
    case "h6":
      return `
###### ${kids().trim()}
`;
    case "p":
      return `
${kids()}
`;
    case "br":
      return "\n";
    case "hr":
      return "\n---\n";
    case "strong":
    case "b":
      return `**${kids()}**`;
    case "em":
    case "i":
      return `*${kids()}*`;
    case "del":
    case "s":
      return `~~${kids()}~~`;
    case "code": {
      const text = kids();
      return text.includes("\n") ? `\`\`\`
${text}
\`\`\`` : `\`${text}\``;
    }
    case "pre": {
      const codeEl = el.querySelector("code");
      if (codeEl) {
        const lang = (_c = ((_b = codeEl.className.match(/language-(\w+)/)) != null ? _b : [])[1]) != null ? _c : "";
        return `
\`\`\`${lang}
${(_d = codeEl.textContent) != null ? _d : ""}
\`\`\`
`;
      }
      return `
\`\`\`
${(_e = el.textContent) != null ? _e : ""}
\`\`\`
`;
    }
    case "a": {
      const href = (_f = el.getAttribute("href")) != null ? _f : "";
      const text = kids().trim();
      return href ? `[${text}](${href})` : text;
    }
    case "img": {
      const src = (_g = el.getAttribute("src")) != null ? _g : "";
      const alt = (_h = el.getAttribute("alt")) != null ? _h : "";
      return `![${alt}](${src})`;
    }
    case "ul":
      return `
${renderList(el, false)}
`;
    case "ol":
      return `
${renderList(el, true)}
`;
    case "li":
      return kids();
    case "blockquote":
      return `
> ${kids().trim().replace(/\n/g, "\n> ")}
`;
    case "table":
      return `
${renderTable(el)}
`;
    case "thead":
    case "tbody":
    case "tfoot":
    case "tr":
      return kids();
    default:
      return kids();
  }
}
function renderList(el, ordered) {
  const lines = [];
  let idx = 1;
  for (const child of Array.from(el.childNodes)) {
    if (child.nodeType !== Node.ELEMENT_NODE)
      continue;
    const tag = child.tagName.toLowerCase();
    if (tag !== "li")
      continue;
    const prefix = ordered ? `${idx++}. ` : "- ";
    const content = nodeToMd(child).trim().replace(/\n/g, "\n   ");
    lines.push(`${prefix}${content}`);
  }
  return lines.join("\n");
}
function renderTable(table) {
  const rows = Array.from(table.querySelectorAll("tr"));
  if (rows.length === 0)
    return "";
  const parsed = rows.map(
    (row) => Array.from(row.querySelectorAll("th, td")).map(
      (cell) => nodeToMd(cell).trim().replace(/\n+/g, " ").replace(/\|/g, "\\|")
    )
  );
  const colCount = Math.max(...parsed.map((r) => r.length));
  parsed.forEach((row) => {
    while (row.length < colCount)
      row.push("");
  });
  const sep = Array(colCount).fill("---");
  return [
    `| ${parsed[0].join(" | ")} |`,
    `| ${sep.join(" | ")} |`,
    ...parsed.slice(1).map((r) => `| ${r.join(" | ")} |`)
  ].join("\n");
}

// src/markdownBuilder.ts
function buildMarkdown(page, settings, existingContent) {
  const frontmatter = buildFrontmatter(page, settings);
  const body = buildBody(page, settings);
  const freshContent = `${frontmatter}
${body}

${SECTION_MARKER}
`;
  if (!existingContent)
    return freshContent;
  const markerIdx = existingContent.indexOf(SECTION_MARKER);
  if (markerIdx !== -1) {
    const userNotes = existingContent.slice(markerIdx + SECTION_MARKER.length);
    return `${frontmatter}
${body}

${SECTION_MARKER}${userNotes}`;
  }
  return settings.missingMarker === "skip" ? existingContent : freshContent;
}
function buildFrontmatter(page, settings) {
  var _a, _b, _c, _d, _e, _f, _g, _h, _i, _j, _k, _l, _m, _n, _o, _p, _q, _r, _s, _t, _u, _v, _w, _x;
  const domain = settings.domain.replace(/\/$/, "");
  const webui = (_b = (_a = page._links) == null ? void 0 : _a.webui) != null ? _b : "";
  const url = webui.startsWith("http") ? webui : `${domain}${webui}`;
  const labels = (_f = (_e = (_d = (_c = page.metadata) == null ? void 0 : _c.labels) == null ? void 0 : _d.results) == null ? void 0 : _e.map((l) => l.name)) != null ? _f : [];
  const parent = (_g = page.ancestors) == null ? void 0 : _g[page.ancestors.length - 1];
  const author = (_m = (_l = (_i = (_h = page.history) == null ? void 0 : _h.createdBy) == null ? void 0 : _i.displayName) != null ? _l : (_k = (_j = page.history) == null ? void 0 : _j.createdBy) == null ? void 0 : _k.username) != null ? _m : "";
  const created = yamlDate((_o = (_n = page.history) == null ? void 0 : _n.createdDate) != null ? _o : "");
  const updated = yamlDate((_q = (_p = page.version) == null ? void 0 : _p.when) != null ? _q : "");
  const lines = [
    "---",
    `confluence_id: ${yamlString(page.id)}`,
    `confluence_url: ${yamlString(url)}`,
    `title: ${yamlString(page.title)}`,
    `space: ${yamlString((_s = (_r = page.space) == null ? void 0 : _r.key) != null ? _s : "")}`,
    `space_name: ${yamlString((_u = (_t = page.space) == null ? void 0 : _t.name) != null ? _u : "")}`,
    `author: ${yamlString(author)}`,
    `created: "${created}"`,
    `updated: "${updated}"`,
    `version: ${(_w = (_v = page.version) == null ? void 0 : _v.number) != null ? _w : 0}`
  ];
  if (labels.length > 0) {
    lines.push("labels:");
    labels.forEach((l) => lines.push(`  - ${yamlString(l)}`));
  } else {
    lines.push("labels: []");
  }
  if (parent) {
    lines.push(`parent: "[[${parent.id}_${slugify(parent.title)}]]"`);
  }
  for (const mapping of (_x = settings.fieldMappings) != null ? _x : []) {
    const value = resolvePath(page, mapping.sourcePath);
    if (value !== void 0 && value !== null) {
      const serialized = Array.isArray(value) ? value.map((v) => String(v)) : String(value);
      if (Array.isArray(serialized)) {
        lines.push(`${mapping.frontmatterKey}:`);
        serialized.forEach((v) => lines.push(`  - ${yamlString(v)}`));
      } else {
        lines.push(`${mapping.frontmatterKey}: ${yamlString(serialized)}`);
      }
    }
  }
  lines.push("---");
  return lines.join("\n");
}
function buildBody(page, settings) {
  var _a, _b, _c;
  let body = storageToMarkdown((_c = (_b = (_a = page.body) == null ? void 0 : _a.storage) == null ? void 0 : _b.value) != null ? _c : "", {
    wikiLinks: settings.wikiLinks
  });
  if (settings.maxBodyLength > 0 && body.length > settings.maxBodyLength) {
    body = body.slice(0, settings.maxBodyLength) + "\n\n\u2026(truncated)";
  }
  return body;
}
function resolvePath(obj, path) {
  return path.split(".").reduce((cur, key) => {
    if (cur !== null && typeof cur === "object") {
      return cur[key];
    }
    return void 0;
  }, obj);
}

// src/settings.ts
var import_obsidian3 = require("obsidian");

// src/i18n.ts
var TRANSLATIONS = {
  en: {
    "setting.title": "Confluence Weaver",
    "setting.connection": "Connection",
    "setting.domain": "Confluence domain",
    "setting.domain.desc": "e.g. https://mycompany.atlassian.net/wiki",
    "setting.authMode": "Auth mode",
    "setting.authMode.basic": "Basic auth (Cloud)",
    "setting.authMode.bearer": "Bearer token (DC/Server)",
    "setting.email": "Email",
    "setting.email.desc": "Used with Basic auth (Cloud)",
    "setting.token": "Personal Access Token",
    "setting.token.desc": "API token (Cloud) or PAT (DC/Server)",
    "setting.testConnection": "Test connection",
    "setting.profiles": "CQL Profiles",
    "setting.addProfile": "+ Add profile",
    "setting.editProfile": "Edit",
    "setting.deleteProfile": "Delete",
    "setting.sync": "Sync Settings",
    "setting.syncOnStartup": "Sync on startup",
    "setting.syncOnStartup.desc": "Run sync when Obsidian opens",
    "setting.syncInterval": "Sync interval (minutes)",
    "setting.syncInterval.desc": "0 = disabled, 1\u20131440",
    "setting.missingMarker": "Missing marker behavior",
    "setting.missingMarker.desc": "What to do when the section marker is absent",
    "setting.missingMarker.overwrite": "Overwrite",
    "setting.missingMarker.skip": "Skip",
    "setting.folderHierarchy": "Preserve folder hierarchy",
    "setting.folderHierarchy.desc": "Mirror Confluence ancestor pages as folders",
    "setting.advanced": "Advanced",
    "setting.maxBodyLength": "Max body length (chars)",
    "setting.maxBodyLength.desc": "0 = unlimited",
    "setting.wikiLinks": "Convert Confluence links to wiki-links",
    "setting.wikiLinks.desc": "Replace [[ac:link]] with Obsidian [[wiki-link]] during conversion",
    "setting.fieldMappings": "Custom field mappings",
    "setting.fieldMappings.desc": "One mapping per line: dotPath \u2192 frontmatterKey (e.g. space.key \u2192 project)",
    "cmd.sync": "Sync Pages",
    "cmd.forceSync": "Force Sync Pages (Overwrite All)",
    "cmd.openLog": "Open Sync Log",
    "cmd.linkJira": "Link Confluence Pages in Jira Notes",
    "notice.linkJira": "Linking Confluence pages in Jira notes\u2026",
    "notice.linkJiraDone": "Linked {count} Confluence URLs in Jira notes.",
    "notice.linkJiraFailed": "Link failed: ",
    "notice.connecting": "Testing connection\u2026",
    "notice.connected": "Connection successful",
    "notice.connectFailed": "Connection failed: ",
    "notice.syncing": "Syncing\u2026",
    "notice.syncDone": "Sync complete",
    "notice.syncFailed": "Sync failed: ",
    "log.title": "Confluence Weaver \u2014 Sync Log",
    "log.profile": "Profile",
    "log.created": "Created",
    "log.updated": "Updated",
    "log.skipped": "Skipped",
    "log.errors": "Errors",
    "log.lastSync": "Last sync",
    "log.never": "Never",
    "log.noStats": "No sync has run yet.",
    "modal.editProfile": "Edit CQL Profile",
    "modal.newProfile": "New CQL Profile",
    "modal.profileName": "Profile name",
    "modal.cql": "CQL query",
    "modal.folder": "Target folder",
    "modal.folder.desc": "Relative path inside the Vault",
    "modal.maxPages": "Max pages",
    "modal.save": "Save",
    "modal.cancel": "Cancel"
  },
  ko: {
    "setting.title": "Confluence Weaver",
    "setting.connection": "\uC5F0\uACB0",
    "setting.domain": "Confluence \uB3C4\uBA54\uC778",
    "setting.domain.desc": "\uC608: https://mycompany.atlassian.net/wiki",
    "setting.authMode": "\uC778\uC99D \uBC29\uC2DD",
    "setting.authMode.basic": "Basic auth (Cloud)",
    "setting.authMode.bearer": "Bearer token (DC/Server)",
    "setting.email": "\uC774\uBA54\uC77C",
    "setting.email.desc": "Basic auth (Cloud) \uC0AC\uC6A9 \uC2DC \uC785\uB825",
    "setting.token": "\uAC1C\uC778 \uC561\uC138\uC2A4 \uD1A0\uD070",
    "setting.token.desc": "API \uD1A0\uD070 (Cloud) \uB610\uB294 PAT (DC/Server)",
    "setting.testConnection": "\uC5F0\uACB0 \uD14C\uC2A4\uD2B8",
    "setting.profiles": "CQL \uD504\uB85C\uD30C\uC77C",
    "setting.addProfile": "+ \uD504\uB85C\uD30C\uC77C \uCD94\uAC00",
    "setting.editProfile": "\uD3B8\uC9D1",
    "setting.deleteProfile": "\uC0AD\uC81C",
    "setting.sync": "\uC2F1\uD06C \uC124\uC815",
    "setting.syncOnStartup": "\uC2DC\uC791 \uC2DC \uC2F1\uD06C",
    "setting.syncOnStartup.desc": "Obsidian \uC5F4\uB9B4 \uB54C \uC790\uB3D9 \uC2F1\uD06C",
    "setting.syncInterval": "\uC2F1\uD06C \uC8FC\uAE30 (\uBD84)",
    "setting.syncInterval.desc": "0 = \uBE44\uD65C\uC131, 1\u20131440",
    "setting.missingMarker": "\uB9C8\uCEE4 \uC5C6\uB294 \uD30C\uC77C \uCC98\uB9AC",
    "setting.missingMarker.desc": "\uC139\uC158 \uB9C8\uCEE4\uAC00 \uC5C6\uC744 \uB54C \uB3D9\uC791",
    "setting.missingMarker.overwrite": "\uB36E\uC5B4\uC4F0\uAE30",
    "setting.missingMarker.skip": "\uAC74\uB108\uB6F0\uAE30",
    "setting.folderHierarchy": "\uACC4\uCE35 \uAD6C\uC870 \uD3F4\uB354 \uBC18\uC601",
    "setting.folderHierarchy.desc": "Confluence \uC0C1\uC704 \uD398\uC774\uC9C0\uB97C \uD3F4\uB354\uB85C \uBC18\uC601",
    "setting.advanced": "\uACE0\uAE09",
    "setting.maxBodyLength": "\uCD5C\uB300 \uBCF8\uBB38 \uAE38\uC774 (\uBB38\uC790)",
    "setting.maxBodyLength.desc": "0 = \uC81C\uD55C \uC5C6\uC74C",
    "setting.wikiLinks": "Confluence \uB9C1\uD06C\uB97C wiki-link\uB85C \uBCC0\uD658",
    "setting.wikiLinks.desc": "\uBCC0\uD658 \uC2DC [[ac:link]]\uB97C Obsidian [[wiki-link]]\uB85C \uB300\uCCB4",
    "setting.fieldMappings": "\uC0AC\uC6A9\uC790 \uC815\uC758 \uD544\uB4DC \uB9E4\uD551",
    "setting.fieldMappings.desc": "\uC904\uB2F9 \uD558\uB098: dotPath \u2192 frontmatterKey (\uC608: space.key \u2192 project)",
    "cmd.sync": "\uD398\uC774\uC9C0 \uC2F1\uD06C",
    "cmd.forceSync": "\uD398\uC774\uC9C0 \uAC15\uC81C \uC2F1\uD06C (\uC804\uCCB4 \uB36E\uC5B4\uC4F0\uAE30)",
    "cmd.openLog": "\uC2F1\uD06C \uB85C\uADF8 \uC5F4\uAE30",
    "cmd.linkJira": "Jira \uB178\uD2B8\uC5D0 Confluence \uD398\uC774\uC9C0 \uC5F0\uACB0",
    "notice.linkJira": "Jira \uB178\uD2B8\uC5D0 Confluence \uD398\uC774\uC9C0\uB97C \uC5F0\uACB0\uD558\uB294 \uC911\u2026",
    "notice.linkJiraDone": "Jira \uB178\uD2B8\uC5D0\uC11C Confluence URL {count}\uAC1C\uB97C wiki-link\uB85C \uBCC0\uD658\uD588\uC2B5\uB2C8\uB2E4.",
    "notice.linkJiraFailed": "\uC5F0\uACB0 \uC2E4\uD328: ",
    "notice.connecting": "\uC5F0\uACB0 \uD14C\uC2A4\uD2B8 \uC911\u2026",
    "notice.connected": "\uC5F0\uACB0 \uC131\uACF5",
    "notice.connectFailed": "\uC5F0\uACB0 \uC2E4\uD328: ",
    "notice.syncing": "\uC2F1\uD06C \uC911\u2026",
    "notice.syncDone": "\uC2F1\uD06C \uC644\uB8CC",
    "notice.syncFailed": "\uC2F1\uD06C \uC2E4\uD328: ",
    "log.title": "Confluence Weaver \u2014 \uC2F1\uD06C \uB85C\uADF8",
    "log.profile": "\uD504\uB85C\uD30C\uC77C",
    "log.created": "\uC0DD\uC131",
    "log.updated": "\uC5C5\uB370\uC774\uD2B8",
    "log.skipped": "\uAC74\uB108\uB700",
    "log.errors": "\uC624\uB958",
    "log.lastSync": "\uB9C8\uC9C0\uB9C9 \uC2F1\uD06C",
    "log.never": "\uC5C6\uC74C",
    "log.noStats": "\uC544\uC9C1 \uC2F1\uD06C\uAC00 \uC2E4\uD589\uB418\uC9C0 \uC54A\uC558\uC2B5\uB2C8\uB2E4.",
    "modal.editProfile": "CQL \uD504\uB85C\uD30C\uC77C \uD3B8\uC9D1",
    "modal.newProfile": "\uC0C8 CQL \uD504\uB85C\uD30C\uC77C",
    "modal.profileName": "\uD504\uB85C\uD30C\uC77C \uC774\uB984",
    "modal.cql": "CQL \uCFFC\uB9AC",
    "modal.folder": "\uB300\uC0C1 \uD3F4\uB354",
    "modal.folder.desc": "Vault \uB0B4 \uC0C1\uB300 \uACBD\uB85C",
    "modal.maxPages": "\uCD5C\uB300 \uD398\uC774\uC9C0 \uC218",
    "modal.save": "\uC800\uC7A5",
    "modal.cancel": "\uCDE8\uC18C"
  }
};
function t(key) {
  var _a, _b, _c;
  const lang = window.navigator.language.startsWith("ko") ? "ko" : "en";
  return (_c = (_b = (_a = TRANSLATIONS[lang]) == null ? void 0 : _a[key]) != null ? _b : TRANSLATIONS.en[key]) != null ? _c : key;
}

// src/cqlProfileModal.ts
var import_obsidian2 = require("obsidian");
var CqlProfileModal = class extends import_obsidian2.Modal {
  constructor(app, profile, onSave) {
    super(app);
    this.profile = { ...profile };
    this.onSave = onSave;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    const isNew = !this.profile.id;
    contentEl.createEl("h2", { text: isNew ? t("modal.newProfile") : t("modal.editProfile") });
    new import_obsidian2.Setting(contentEl).setName(t("modal.profileName")).addText(
      (text) => text.setValue(this.profile.name).onChange((v) => {
        this.profile.name = v;
      })
    );
    new import_obsidian2.Setting(contentEl).setName(t("modal.cql")).addTextArea((area) => {
      area.setValue(this.profile.cql).onChange((v) => {
        this.profile.cql = v;
      });
      area.inputEl.rows = 4;
      area.inputEl.addClass("cw-textarea");
    });
    new import_obsidian2.Setting(contentEl).setName(t("modal.folder")).setDesc(t("modal.folder.desc")).addText(
      (text) => text.setPlaceholder("Confluence").setValue(this.profile.folder).onChange((v) => {
        this.profile.folder = v;
      })
    );
    new import_obsidian2.Setting(contentEl).setName(t("modal.maxPages")).addText(
      (text) => text.setValue(String(this.profile.maxPages)).onChange((v) => {
        this.profile.maxPages = Math.max(1, parseInt(v) || 50);
      })
    );
    new import_obsidian2.Setting(contentEl).addButton(
      (btn) => btn.setButtonText(t("modal.save")).setCta().onClick(() => {
        if (isNew)
          this.profile.id = Date.now().toString();
        this.onSave(this.profile);
        this.close();
      })
    ).addButton(
      (btn) => btn.setButtonText(t("modal.cancel")).onClick(() => this.close())
    );
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/settings.ts
var ConfluenceWeaverSettingTab = class extends import_obsidian3.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: t("setting.title") });
    containerEl.createEl("h3", { text: t("setting.connection") });
    new import_obsidian3.Setting(containerEl).setName(t("setting.domain")).setDesc(t("setting.domain.desc")).addText(
      (text) => text.setPlaceholder("https://mycompany.atlassian.net/wiki").setValue(this.plugin.settings.domain).onChange(async (v) => {
        this.plugin.settings.domain = v.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName(t("setting.authMode")).addDropdown(
      (drop) => drop.addOption("basic", t("setting.authMode.basic")).addOption("bearer", t("setting.authMode.bearer")).setValue(this.plugin.settings.authMode).onChange(async (v) => {
        this.plugin.settings.authMode = v;
        await this.plugin.saveSettings();
        this.display();
      })
    );
    if (this.plugin.settings.authMode === "basic") {
      new import_obsidian3.Setting(containerEl).setName(t("setting.email")).setDesc(t("setting.email.desc")).addText(
        (text) => text.setValue(this.plugin.settings.email).onChange(async (v) => {
          this.plugin.settings.email = v.trim();
          await this.plugin.saveSettings();
        })
      );
    }
    new import_obsidian3.Setting(containerEl).setName(t("setting.token")).setDesc(t("setting.token.desc")).addText((text) => {
      text.setValue(this.plugin.settings.token).onChange(async (v) => {
        this.plugin.settings.token = v.trim();
        await this.plugin.saveSettings();
      });
      text.inputEl.type = "password";
    });
    new import_obsidian3.Setting(containerEl).addButton(
      (btn) => btn.setButtonText(t("setting.testConnection")).onClick(async () => {
        new import_obsidian3.Notice(t("notice.connecting"));
        try {
          await new ConfluenceClient(this.plugin.settings).testConnection();
          new import_obsidian3.Notice(t("notice.connected"));
        } catch (e) {
          new import_obsidian3.Notice(`${t("notice.connectFailed")}${e.message}`);
        }
      })
    );
    containerEl.createEl("h3", { text: t("setting.profiles") });
    for (const profile of this.plugin.settings.profiles) {
      const setting = new import_obsidian3.Setting(containerEl).setName(profile.name || "(unnamed)").setDesc(profile.cql);
      setting.addToggle(
        (toggle) => toggle.setValue(profile.enabled).onChange(async (v) => {
          profile.enabled = v;
          await this.plugin.saveSettings();
        })
      );
      setting.addButton(
        (btn) => btn.setButtonText(t("setting.editProfile")).onClick(
          () => new CqlProfileModal(this.app, profile, async (updated) => {
            const idx = this.plugin.settings.profiles.findIndex((p) => p.id === updated.id);
            if (idx !== -1)
              this.plugin.settings.profiles[idx] = updated;
            await this.plugin.saveSettings();
            this.display();
          }).open()
        )
      );
      setting.addButton(
        (btn) => btn.setButtonText(t("setting.deleteProfile")).setWarning().onClick(async () => {
          this.plugin.settings.profiles = this.plugin.settings.profiles.filter(
            (p) => p.id !== profile.id
          );
          await this.plugin.saveSettings();
          this.display();
        })
      );
    }
    new import_obsidian3.Setting(containerEl).addButton(
      (btn) => btn.setButtonText(t("setting.addProfile")).onClick(() => {
        const blank = {
          id: "",
          name: "",
          cql: "",
          folder: "Confluence",
          maxPages: 50,
          enabled: true
        };
        new CqlProfileModal(this.app, blank, async (created) => {
          this.plugin.settings.profiles.push(created);
          await this.plugin.saveSettings();
          this.display();
        }).open();
      })
    );
    containerEl.createEl("h3", { text: t("setting.sync") });
    new import_obsidian3.Setting(containerEl).setName(t("setting.syncOnStartup")).setDesc(t("setting.syncOnStartup.desc")).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.syncOnStartup).onChange(async (v) => {
        this.plugin.settings.syncOnStartup = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName(t("setting.syncInterval")).setDesc(t("setting.syncInterval.desc")).addText(
      (text) => text.setValue(String(this.plugin.settings.syncInterval)).onChange(async (v) => {
        this.plugin.settings.syncInterval = Math.min(1440, Math.max(0, parseInt(v) || 0));
        await this.plugin.saveSettings();
        this.plugin.scheduler.restart();
      })
    );
    new import_obsidian3.Setting(containerEl).setName(t("setting.missingMarker")).setDesc(t("setting.missingMarker.desc")).addDropdown(
      (drop) => drop.addOption("overwrite", t("setting.missingMarker.overwrite")).addOption("skip", t("setting.missingMarker.skip")).setValue(this.plugin.settings.missingMarker).onChange(async (v) => {
        this.plugin.settings.missingMarker = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName(t("setting.folderHierarchy")).setDesc(t("setting.folderHierarchy.desc")).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.folderHierarchy).onChange(async (v) => {
        this.plugin.settings.folderHierarchy = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName(t("setting.wikiLinks")).setDesc(t("setting.wikiLinks.desc")).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.wikiLinks).onChange(async (v) => {
        this.plugin.settings.wikiLinks = v;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: t("setting.advanced") });
    new import_obsidian3.Setting(containerEl).setName(t("setting.maxBodyLength")).setDesc(t("setting.maxBodyLength.desc")).addText(
      (text) => text.setValue(String(this.plugin.settings.maxBodyLength)).onChange(async (v) => {
        this.plugin.settings.maxBodyLength = Math.max(0, parseInt(v) || 0);
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName(t("setting.fieldMappings")).setDesc(t("setting.fieldMappings.desc")).addTextArea((area) => {
      const toText = () => {
        var _a;
        return ((_a = this.plugin.settings.fieldMappings) != null ? _a : []).map((m) => `${m.sourcePath} \u2192 ${m.frontmatterKey}`).join("\n");
      };
      area.setValue(toText()).onChange(async (raw) => {
        this.plugin.settings.fieldMappings = raw.split("\n").map((line) => line.trim()).filter((line) => line.includes("\u2192") || line.includes("->")).map((line) => {
          const [src, tgt] = line.split(/→|->/).map((s) => s.trim());
          return { sourcePath: src, frontmatterKey: tgt };
        }).filter((m) => m.sourcePath && m.frontmatterKey);
        await this.plugin.saveSettings();
      });
      area.inputEl.rows = 5;
      area.inputEl.addClass("cw-textarea");
      area.inputEl.addClass("cw-textarea-mono");
    });
  }
};

// src/syncScheduler.ts
var SyncScheduler = class {
  constructor(plugin) {
    this.plugin = plugin;
    this.intervalId = null;
  }
  start() {
    if (this.plugin.settings.syncOnStartup) {
      window.setTimeout(() => this.plugin.syncPages(false), 3e3);
    }
    this.scheduleInterval();
  }
  restart() {
    this.stop();
    this.scheduleInterval();
  }
  stop() {
    if (this.intervalId !== null) {
      window.clearInterval(this.intervalId);
      this.intervalId = null;
    }
  }
  scheduleInterval() {
    const minutes = this.plugin.settings.syncInterval;
    if (minutes > 0) {
      this.intervalId = window.setInterval(
        () => this.plugin.syncPages(false),
        minutes * 60 * 1e3
      );
    }
  }
};

// src/syncLogView.ts
var import_obsidian4 = require("obsidian");
var VIEW_TYPE_SYNC_LOG = "confluence-weaver-sync-log";
var SyncLogView = class extends import_obsidian4.ItemView {
  constructor(leaf) {
    super(leaf);
    this.stats = [];
  }
  getViewType() {
    return VIEW_TYPE_SYNC_LOG;
  }
  getDisplayText() {
    return t("log.title");
  }
  getIcon() {
    return "refresh-cw";
  }
  async onOpen() {
    this.render();
  }
  async onClose() {
  }
  setStats(stats) {
    this.stats = stats;
    this.render();
  }
  render() {
    const root = this.containerEl.children[1];
    root.empty();
    root.createEl("h4", { text: t("log.title"), cls: "cw-log-heading" });
    if (this.stats.length === 0) {
      root.createEl("p", { text: t("log.noStats"), cls: "cw-log-empty" });
      return;
    }
    for (const stat of this.stats) {
      const section = root.createEl("div", { cls: "cw-log-section" });
      section.createEl("h5", { text: stat.profileName, cls: "cw-log-profile" });
      const table = section.createEl("table", { cls: "cw-log-table" });
      const addRow = (label, value) => {
        const tr = table.createEl("tr");
        tr.createEl("td", { text: label, cls: "cw-log-label" });
        tr.createEl("td", { text: String(value), cls: "cw-log-value" });
      };
      addRow(t("log.created"), stat.created);
      addRow(t("log.updated"), stat.updated);
      addRow(t("log.skipped"), stat.skipped);
      addRow(t("log.errors"), stat.errors);
      addRow(t("log.lastSync"), stat.lastSync ? stat.lastSync.replace("T", " ").slice(0, 19) : t("log.never"));
    }
  }
};

// src/main.ts
var DEFAULT_SETTINGS = {
  domain: "",
  authMode: "basic",
  email: "",
  token: "",
  profiles: [],
  syncOnStartup: false,
  syncInterval: 0,
  missingMarker: "overwrite",
  folderHierarchy: false,
  maxBodyLength: 0,
  wikiLinks: true,
  fieldMappings: []
};
var ConfluenceWeaverPlugin = class extends import_obsidian5.Plugin {
  constructor() {
    super(...arguments);
    this.settings = { ...DEFAULT_SETTINGS };
    this.scheduler = new SyncScheduler(this);
    this.syncStats = [];
  }
  async onload() {
    await this.loadSettings();
    this.registerView(VIEW_TYPE_SYNC_LOG, (leaf) => new SyncLogView(leaf));
    this.addCommand({
      id: "sync-pages",
      name: t("cmd.sync"),
      callback: () => this.syncPages(false)
    });
    this.addCommand({
      id: "force-sync-pages",
      name: t("cmd.forceSync"),
      callback: () => this.syncPages(true)
    });
    this.addCommand({
      id: "open-sync-log",
      name: t("cmd.openLog"),
      callback: () => this.openSyncLog()
    });
    this.addCommand({
      id: "link-jira-weaver-pages",
      name: t("cmd.linkJira"),
      callback: () => this.runJiraWeaverBridge()
    });
    this.addSettingTab(new ConfluenceWeaverSettingTab(this.app, this));
    this.scheduler.start();
  }
  onunload() {
    this.scheduler.stop();
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async syncPages(forceOverwrite) {
    var _a, _b;
    const active = this.settings.profiles.filter((p) => p.enabled);
    if (active.length === 0) {
      new import_obsidian5.Notice("Confluence Weaver: No enabled CQL profiles.");
      return;
    }
    if (!this.settings.domain || !this.settings.token) {
      new import_obsidian5.Notice("Confluence Weaver: Configure domain and token in settings first.");
      return;
    }
    new import_obsidian5.Notice(t("notice.syncing"));
    const client = new ConfluenceClient(this.settings);
    const fm = new FileManager(this.app);
    const allStats = [];
    for (const profile of active) {
      const stats = {
        profileId: profile.id,
        profileName: profile.name,
        created: 0,
        updated: 0,
        skipped: 0,
        errors: 0,
        lastSync: new Date().toISOString()
      };
      try {
        const summaries = await client.searchCQL(profile.cql, profile.maxPages);
        for (const summary of summaries) {
          try {
            const page = await client.getPage(summary.id);
            const filePath = fm.resolveFilePath(page, profile.folder, this.settings.folderHierarchy);
            const existing = await fm.readFile(filePath);
            if (!forceOverwrite && existing) {
              const versionMatch = existing.match(/^version:\s*(\d+)/m);
              if (versionMatch && parseInt(versionMatch[1]) >= ((_b = (_a = page.version) == null ? void 0 : _a.number) != null ? _b : 0)) {
                stats.skipped++;
                continue;
              }
            }
            const content = buildMarkdown(
              page,
              this.settings,
              forceOverwrite ? void 0 : existing != null ? existing : void 0
            );
            if (existing && content === existing) {
              stats.skipped++;
              continue;
            }
            const result = await fm.writeFile(filePath, content);
            result === "created" ? stats.created++ : stats.updated++;
          } catch (e) {
            console.error(`Confluence Weaver: page ${summary.id}`, e);
            stats.errors++;
          }
        }
      } catch (e) {
        console.error(`Confluence Weaver: profile "${profile.name}"`, e);
        new import_obsidian5.Notice(`${t("notice.syncFailed")}${e.message}`);
        stats.errors++;
      }
      allStats.push(stats);
    }
    this.syncStats = allStats;
    this.refreshLogView();
    new import_obsidian5.Notice(t("notice.syncDone"));
  }
  refreshLogView() {
    for (const leaf of this.app.workspace.getLeavesOfType(VIEW_TYPE_SYNC_LOG)) {
      if (leaf.view instanceof SyncLogView)
        leaf.view.setStats(this.syncStats);
    }
  }
  async runJiraWeaverBridge() {
    new import_obsidian5.Notice(t("notice.linkJira"));
    try {
      const count = await linkJiraPages(this.app);
      new import_obsidian5.Notice(t("notice.linkJiraDone").replace("{count}", String(count)));
    } catch (e) {
      new import_obsidian5.Notice(`${t("notice.linkJiraFailed")}${e.message}`);
    }
  }
  async openSyncLog() {
    const existing = this.app.workspace.getLeavesOfType(VIEW_TYPE_SYNC_LOG);
    if (existing.length > 0) {
      this.app.workspace.revealLeaf(existing[0]);
      return;
    }
    const leaf = this.app.workspace.getRightLeaf(false);
    if (leaf) {
      await leaf.setViewState({ type: VIEW_TYPE_SYNC_LOG, active: true });
      this.app.workspace.revealLeaf(leaf);
    }
  }
};
